class_name CreditsData
extends RefCounted
## Generated by tools/audio.sh from the CC-BY rows of assets_src/audio/LICENSES.csv.
## Do not edit: add the row to the manifest and run tools/audio.sh.

const AUDIO := [
]
