extends Node
## Sound effects and music. Every sound is generated by tools/gen_audio.gd (original, no
## licensed assets). SFX play through a small pool of players with a per-sound rate limit,
## so a wand firing 40 bolts a second makes a crackle, not a wall of noise. Music crossfades.
## Two buses, SFX and Music, are created in code and follow the Sound / Music settings.

const POOL := 14
## Minimum seconds between two plays of the same sound.
const GAP := {"cast_spark": 0.045, "hit": 0.03, "crit": 0.05, "eshot": 0.06, "cast_laser": 0.05, "coin": 0.04,
	"kill": 0.04, "burn": 0.15, "cast_fan": 0.08, "cast_missile": 0.06, "cast_chain": 0.05, "trigger": 0.06}
## Which cast sound each shooting spell uses.
const CAST := {&"mote": "cast_spark", &"lance": "cast_laser", &"fan": "cast_fan", &"burst": "cast_boom",
	&"moths": "cast_missile", &"seed": "cast_spark", &"wheel": "cast_orbit", &"needle": "cast_laser",
	&"ember": "cast_fire", &"spark": "cast_chain", &"frost": "cast_ice", &"disc": "cast_orbit", &"mine": "cast_boom",
	&"static": "cast_chain", &"null_orb": "cast_orbit"}

var _streams: Dictionary = {}
var _players: Array[AudioStreamPlayer] = []
var _next := 0
var _last: Dictionary = {}
var _music_a: AudioStreamPlayer
var _music_b: AudioStreamPlayer
var _track := ""
var _tween: Tween
var sound_on := true
var music_on := true


func _ready() -> void:
	_setup()


## Creates buses and players once (lazily too: headless test runs call sfx() before _ready).
func _setup() -> void:
	if not _players.is_empty():
		return
	process_mode = Node.PROCESS_MODE_ALWAYS
	_ensure_bus("SFX")
	_ensure_bus("Music")
	for i in POOL:
		var p := AudioStreamPlayer.new()
		p.bus = "SFX"
		add_child(p)
		_players.append(p)
	_music_a = AudioStreamPlayer.new()
	_music_b = AudioStreamPlayer.new()
	for m in [_music_a, _music_b]:
		m.bus = "Music"
		m.volume_db = -80.0
		add_child(m)
	Events.enemy_killed.connect(func(_k: StringName, _p: Vector2) -> void: sfx("kill", 0.12))
	Events.player_hurt.connect(func(_a: float) -> void: sfx("hurt"))
	Events.room_cleared.connect(func() -> void: sfx("door"))
	Events.boss_defeated.connect(func() -> void: sfx("bigboom"))
	apply(Game.settings())


func _ensure_bus(name: String) -> void:
	if AudioServer.get_bus_index(name) >= 0:
		return
	AudioServer.add_bus()
	var i := AudioServer.bus_count - 1
	AudioServer.set_bus_name(i, name)
	AudioServer.set_bus_send(i, "Master")


func apply(settings: Dictionary) -> void:
	# Game applies saved settings before this node's _ready: make sure the buses exist
	_ensure_bus("SFX")
	_ensure_bus("Music")
	sound_on = bool(settings.get("sound", true))
	music_on = bool(settings.get("music", true))
	AudioServer.set_bus_mute(AudioServer.get_bus_index("SFX"), not sound_on)
	AudioServer.set_bus_mute(AudioServer.get_bus_index("Music"), not music_on)


func stream(name: String) -> AudioStream:
	if not _streams.has(name):
		var path := "res://assets/audio/%s.wav" % name
		_streams[name] = load(path) if ResourceLoader.exists(path) else null
	return _streams[name]


## Plays a sound effect. `jitter` randomises the pitch by up to that fraction.
func sfx(name: String, jitter := 0.06, volume_db := 0.0) -> void:
	if not sound_on:
		return
	_setup()
	var now := Time.get_ticks_msec() / 1000.0
	if now - float(_last.get(name, -9.0)) < float(GAP.get(name, 0.02)):
		return
	_last[name] = now
	var s := stream("sfx_" + name)
	if s == null or not is_inside_tree():
		return
	var p := _players[_next]
	_next = (_next + 1) % POOL
	p.stream = s
	p.pitch_scale = 1.0 + randf_range(-jitter, jitter)
	p.volume_db = volume_db
	p.play()


func cast(spell_id: StringName) -> void:
	sfx(CAST.get(spell_id, "cast_spark"), 0.08, -2.0)


## Crossfades to a music track: title | grove | boss | "" (silence).
func music(track: String, fade := 0.8) -> void:
	if track == _track:
		return
	_setup()
	if not is_inside_tree():
		return
	_track = track
	var incoming := _music_b if _music_a.playing and _music_a.volume_db > -40.0 else _music_a
	var outgoing := _music_a if incoming == _music_b else _music_b
	if _tween:
		_tween.kill()
	_tween = create_tween().set_parallel(true)
	if track != "":
		var s := stream("music_" + track)
		if s:
			incoming.stream = s
			incoming.volume_db = -40.0
			incoming.play()
			_tween.tween_property(incoming, "volume_db", -6.0, fade)
	_tween.tween_property(outgoing, "volume_db", -80.0, fade)
	_tween.chain().tween_callback(outgoing.stop)
