extends Node
## Sound effects and music (D8, design-plan §9). Every sound is generated by tools/audio.sh
## (original, no licensed assets; assets_src/audio/LICENSES.csv lists each file).
##
## Buses, created in code:
##   Master    a hard limiter at -1 dB
##   Music     ducked by a sidechain compressor keyed from Critical
##   SFX       combat and world sounds
##   Critical  sends into SFX: getting hurt, telegraphs, boss moments, stingers. The music
##             ducks under it, so the sounds that matter are never masked.
##   UI        menus
## Voices: three classes (critical, combat, ui), each its own small pool. A new sound takes a
## free voice of its class, or steals the oldest one in that class; a crowd of bolts can never
## cut off a telegraph. Sounds with variants play through an AudioStreamRandomizer.
##
## Music: title | shop | cellar | grove | boss. The two areas are three stems in an
## AudioStreamSynchronized (base; drums in combat; the lead in elite rooms), the boss is an
## AudioStreamInteractive (an intro that hands over to its loop) whose phase-2 layer switches
## in on the next bar. Tracks crossfade; stingers play on Critical.

const VOICES := {"critical": 4, "combat": 12, "ui": 3}
const CLASS_BUS := {"critical": "Critical", "combat": "SFX", "ui": "UI"}
const CRITICAL := ["hurt", "tele", "tele_short", "tele_mid", "tele_long", "phase", "roar", "slam", "fuse_pop", "low_hp",
	"copy_cast", "ctrl_z", "select_all", "derail", "bigboom", "armor_break", "ward_break"]
const UI := ["ui", "ui_back", "ui_open", "ui_close", "ui_equip", "ui_drag", "ui_drop", "swap", "deny", "buy"]
## Minimum seconds between two plays of the same sound.
const GAP := {"cast_spark": 0.045, "hit": 0.03, "crit": 0.05, "eshot": 0.06, "cast_laser": 0.05, "coin": 0.04,
	"kill": 0.04, "burn": 0.15, "cast_fan": 0.08, "cast_missile": 0.06, "cast_chain": 0.05, "trigger": 0.06,
	"hit_fire": 0.04, "hit_ice": 0.04, "hit_static": 0.04, "hit_arcane": 0.04, "hit_void": 0.04, "hit_armor": 0.05,
	"hit_ward": 0.05, "hit_shield": 0.05, "eshot_ring": 0.1, "eshot_laser": 0.06, "fuse": 0.1, "chomp": 0.2}
## Which cast sound each shooting spell uses (one timbre per element).
const CAST := {&"mote": "cast_spark", &"lance": "cast_laser", &"fan": "cast_fan", &"burst": "cast_boom",
	&"moths": "cast_missile", &"seed": "cast_spark", &"wheel": "cast_orbit", &"needle": "cast_laser",
	&"ember": "cast_fire", &"spark": "cast_static", &"frost": "cast_ice", &"disc": "cast_orbit", &"mine": "cast_boom",
	&"static": "cast_static", &"null_orb": "cast_void", &"firewall": "cast_fire", &"bitrot": "cast_arcane",
	&"hexcursor": "cast_arcane", &"ping": "cast_arcane", &"daemon": "cast_arcane", &"turret": "cast_boom", &"duck": "cast_spark",
	&"storm_protocol": "cast_static", &"singularity": "cast_void", &"meltdown": "cast_fire", &"absolute_zero": "cast_ice",
	&"replicator": "cast_spark", &"exploit_needle": "cast_laser"}
## The hit a spell's element makes (by its cast sound).
const HIT := {"cast_fire": "hit_fire", "cast_ice": "hit_ice", "cast_static": "hit_static", "cast_chain": "hit_static",
	"cast_arcane": "hit_arcane", "cast_void": "hit_void"}
## Music: stems per track, and the tempo that sets where a bar starts.
const TRACKS := {
	"title": {"stems": ["music_title"]},
	"shop": {"stems": ["music_shop"]},
	"cellar": {"stems": ["music_cellar_base", "music_cellar_drums", "music_cellar_lead"], "layers": ["", "drums", "lead"]},
	"grove": {"stems": ["music_grove_base", "music_grove_drums", "music_grove_lead"], "layers": ["", "drums", "lead"]},
	"boss": {"intro": "music_boss_intro", "stems": ["music_boss_loop", "music_boss_p2"], "layers": ["", "p2"], "bpm": 128.0, "intro_bars": 4},
}
const MUSIC_DB := -4.0
const LAYER_OFF_DB := -60.0

var _streams: Dictionary = {}
var _voices: Dictionary = {}       # class -> Array[AudioStreamPlayer]
var _started: Dictionary = {}      # player -> ticks it started (for stealing the oldest)
var _last: Dictionary = {}
var _music_a: AudioStreamPlayer
var _music_b: AudioStreamPlayer
var _sting: AudioStreamPlayer
var _track := ""
var _track_t0 := 0
var _tween: Tween
var _layers: Dictionary = {}       # layer name -> [AudioStreamSynchronized, index]
var _layer_on: Dictionary = {}
var _layer_tw: Dictionary = {}
var _built: Dictionary = {}        # track -> AudioStream
var sound_on := true
var music_on := true


func _ready() -> void:
	_setup()


## Creates buses and players once (lazily too: headless test runs call sfx() before _ready).
func _setup() -> void:
	if not _voices.is_empty():
		return
	process_mode = Node.PROCESS_MODE_ALWAYS
	_buses()
	for c in VOICES:
		var arr: Array[AudioStreamPlayer] = []
		for i in VOICES[c]:
			var p := AudioStreamPlayer.new()
			p.bus = CLASS_BUS[c]
			add_child(p)
			arr.append(p)
		_voices[c] = arr
	_music_a = AudioStreamPlayer.new()
	_music_b = AudioStreamPlayer.new()
	for m in [_music_a, _music_b]:
		m.bus = "Music"
		m.volume_db = -80.0
		add_child(m)
	_sting = AudioStreamPlayer.new()
	_sting.bus = "Critical"
	add_child(_sting)
	Events.player_hurt.connect(func(_a: float) -> void: sfx("hurt"))
	Events.room_cleared.connect(func() -> void: sting("clear"))
	Events.boss_defeated.connect(func() -> void: sfx("bigboom"))
	apply(Game.settings())


## The bus layout above. Order matters: a bus only sends to a bus before it.
func _buses() -> void:
	_ensure_bus("SFX", "Master")
	_ensure_bus("Music", "Master")
	_ensure_bus("Critical", "SFX")
	_ensure_bus("UI", "Master")
	var master := AudioServer.get_bus_index("Master")
	if AudioServer.get_bus_effect_count(master) == 0:
		var lim := AudioEffectHardLimiter.new()
		lim.ceiling_db = -1.0
		AudioServer.add_bus_effect(master, lim)
	var music := AudioServer.get_bus_index("Music")
	if AudioServer.get_bus_effect_count(music) == 0:
		var duck := AudioEffectCompressor.new()
		duck.sidechain = &"Critical"
		duck.threshold = -26.0
		duck.ratio = 4.0
		duck.attack_us = 5000.0
		duck.release_ms = 350.0
		AudioServer.add_bus_effect(music, duck)


func _ensure_bus(name: String, send: String) -> void:
	if AudioServer.get_bus_index(name) >= 0:
		return
	AudioServer.add_bus()
	var i := AudioServer.bus_count - 1
	AudioServer.set_bus_name(i, name)
	AudioServer.set_bus_send(i, send)


func apply(settings: Dictionary) -> void:
	# Game applies saved settings before this node's _ready: make sure the buses exist
	_buses()
	sound_on = bool(settings.get("sound", true))
	music_on = bool(settings.get("music", true))
	for b in ["SFX", "UI"]:
		AudioServer.set_bus_mute(AudioServer.get_bus_index(b), not sound_on)
	AudioServer.set_bus_mute(AudioServer.get_bus_index("Music"), not music_on)


func stream(name: String) -> AudioStream:
	if not _streams.has(name):
		var path := "res://assets/audio/%s.wav" % name
		var s: AudioStream = load(path) if ResourceLoader.exists(path) else null
		# variants (x_2, x_3) play through a randomizer that never repeats one twice in a row
		if s and ResourceLoader.exists("res://assets/audio/%s_2.wav" % name):
			var r := AudioStreamRandomizer.new()
			r.playback_mode = AudioStreamRandomizer.PLAYBACK_RANDOM_NO_REPEATS
			r.random_pitch = 1.0
			r.random_volume_offset_db = 1.5
			r.add_stream(-1, s)
			var k := 2
			while ResourceLoader.exists("res://assets/audio/%s_%d.wav" % [name, k]):
				r.add_stream(-1, load("res://assets/audio/%s_%d.wav" % [name, k]))
				k += 1
			s = r
		_streams[name] = s
	return _streams[name]


## The voice class of a sound.
static func voice_class(name: String) -> String:
	if name in CRITICAL:
		return "critical"
	return "ui" if name in UI else "combat"


## Plays a sound effect. `jitter` randomises the pitch by up to that fraction.
func sfx(name: String, jitter := 0.06, volume_db := 0.0) -> void:
	if not sound_on or Game.quiet > 0:
		return
	_setup()
	var now := Time.get_ticks_msec() / 1000.0
	if now - float(_last.get(name, -9.0)) < float(GAP.get(name, 0.02)):
		return
	_last[name] = now
	var s := stream("sfx_" + name)
	if s == null or not is_inside_tree():
		return
	var p := _voice(voice_class(name))
	p.stream = s
	p.pitch_scale = 1.0 + randf_range(-jitter, jitter)
	p.volume_db = volume_db
	p.play()
	_started[p] = Time.get_ticks_msec()


## A free voice of the class, or the one that started longest ago.
func _voice(c: String) -> AudioStreamPlayer:
	var pool: Array = _voices[c]
	var oldest: AudioStreamPlayer = pool[0]
	for p: AudioStreamPlayer in pool:
		if not p.playing:
			return p
		if int(_started.get(p, 0)) < int(_started.get(oldest, 0)):
			oldest = p
	return oldest


func cast(spell_id: StringName) -> void:
	sfx(CAST.get(spell_id, "cast_spark"), 0.08, -2.0)


## The hit sound a spell's element makes.
static func hit_for(spell_id: StringName) -> String:
	var h: Variant = _hit_cache.get(spell_id)
	if h == null:
		h = HIT.get(CAST.get(spell_id, ""), "hit")
		_hit_cache[spell_id] = h
	return h


static var _hit_cache := {}


## A stinger (clear, reward, boss, victory, defeat): on Critical, so the music ducks under it.
func sting(name: String) -> void:
	if not music_on or Game.quiet > 0 or not is_inside_tree():
		return
	_setup()
	var s := stream("sting_" + name)
	if s:
		_sting.stream = s
		_sting.play()


## On the player's death the music sinks behind a closing low-pass for about a second
## (design-plan §10); the next music() call lifts it.
var _lowpass: AudioEffectLowPassFilter
var _sweep: Tween


func death_sweep() -> void:
	if not is_inside_tree():
		return
	var bus := AudioServer.get_bus_index("Music")
	if bus < 0:
		return
	if _lowpass == null:
		_lowpass = AudioEffectLowPassFilter.new()
		AudioServer.add_bus_effect(bus, _lowpass)
	for i in AudioServer.get_bus_effect_count(bus):
		if AudioServer.get_bus_effect(bus, i) == _lowpass:
			AudioServer.set_bus_effect_enabled(bus, i, true)
	_lowpass.cutoff_hz = 16000.0
	if _sweep:
		_sweep.kill()
	_sweep = create_tween()
	_sweep.tween_property(_lowpass, "cutoff_hz", 500.0, 1.0).set_ease(Tween.EASE_OUT).set_trans(Tween.TRANS_EXPO)


func _clear_sweep() -> void:
	if _lowpass == null:
		return
	if _sweep:
		_sweep.kill()
	var bus := AudioServer.get_bus_index("Music")
	for i in AudioServer.get_bus_effect_count(bus):
		if AudioServer.get_bus_effect(bus, i) == _lowpass:
			AudioServer.set_bus_effect_enabled(bus, i, false)


## The stream for a track, built once: a single loop, a synchronized set of stems, or (the
## boss) an interactive stream whose intro advances into the synchronized loop.
func track_stream(track: String) -> AudioStream:
	if _built.has(track):
		return _built[track]
	var def: Dictionary = TRACKS[track]
	var stems: Array = def["stems"]
	var s: AudioStream
	if stems.size() == 1:
		s = stream(stems[0])
	else:
		var sync := AudioStreamSynchronized.new()
		sync.stream_count = stems.size()
		for i in stems.size():
			sync.set_sync_stream(i, stream(stems[i]))
			sync.set_sync_stream_volume(i, 0.0 if i == 0 else LAYER_OFF_DB)
		s = sync
		if def.has("intro"):
			var inter := AudioStreamInteractive.new()
			inter.clip_count = 2
			inter.set_clip_name(0, &"intro")
			inter.set_clip_stream(0, stream(def["intro"]))
			inter.set_clip_auto_advance(0, AudioStreamInteractive.AUTO_ADVANCE_ENABLED)
			inter.set_clip_auto_advance_next_clip(0, 1)
			inter.set_clip_name(1, &"loop")
			inter.set_clip_stream(1, sync)
			inter.initial_clip = 0
			s = inter
	_built[track] = s
	return s


## Crossfades to a music track: title | shop | cellar | grove | boss | "" (silence). Every
## optional layer starts off.
func music(track: String, fade := 0.8) -> void:
	_clear_sweep()
	if track == _track:
		return
	_setup()
	_track = track
	_track_t0 = Time.get_ticks_msec()
	_layers.clear()
	_layer_on.clear()
	var s: AudioStream = track_stream(track) if TRACKS.has(track) else null
	if s:
		# the layer bookkeeping does not need a running tree (the tests check it headless)
		var def: Dictionary = TRACKS[track]
		var sync: AudioStreamSynchronized = s if s is AudioStreamSynchronized else (
			(s as AudioStreamInteractive).get_clip_stream(1) if s is AudioStreamInteractive else null)
		if sync:
			var names: Array = def["layers"]
			for i in names.size():
				sync.set_sync_stream_volume(i, 0.0 if i == 0 else LAYER_OFF_DB)
				if names[i] != "":
					_layers[names[i]] = [sync, i]
	if not is_inside_tree():
		return
	var incoming := _music_b if _music_a.playing and _music_a.volume_db > -40.0 else _music_a
	var outgoing := _music_a if incoming == _music_b else _music_b
	if _tween:
		_tween.kill()
	_tween = create_tween().set_parallel(true)
	if s:
		incoming.stream = s
		incoming.volume_db = -40.0
		incoming.play()
		_tween.tween_property(incoming, "volume_db", MUSIC_DB, fade)
	_tween.tween_property(outgoing, "volume_db", -80.0, fade)
	_tween.chain().tween_callback(outgoing.stop)


func current_track() -> String:
	return _track


## Turns an optional layer of the playing track on or off (drums, lead, p2). The boss's
## phase-2 layer waits for the next bar so it lands on the beat.
func layer(name: String, on: bool, fade := 0.6) -> void:
	if not _layers.has(name) or bool(_layer_on.get(name, false)) == on:
		return
	_layer_on[name] = on
	var def: Dictionary = TRACKS[_track]
	var wait := 0.0
	if on and def.has("bpm"):
		var bar := 4.0 * 60.0 / float(def["bpm"])
		var since := (Time.get_ticks_msec() - _track_t0) / 1000.0 - bar * float(def.get("intro_bars", 0))
		wait = bar - fposmod(since, bar) if since > 0.0 else -since
	var ref: Array = _layers[name]
	var sync: AudioStreamSynchronized = ref[0]
	var i: int = ref[1]
	if _layer_tw.has(name) and _layer_tw[name]:
		(_layer_tw[name] as Tween).kill()
	if not is_inside_tree():
		sync.set_sync_stream_volume(i, 0.0 if on else LAYER_OFF_DB)
		return
	var tw := create_tween()
	if wait > 0.0:
		tw.tween_interval(wait)
	tw.tween_method(func(db: float) -> void: sync.set_sync_stream_volume(i, db),
		sync.get_sync_stream_volume(i), 0.0 if on else LAYER_OFF_DB, 0.05 if wait > 0.0 else fade)
	_layer_tw[name] = tw


func layer_on(name: String) -> bool:
	return bool(_layer_on.get(name, false))


## Web: publishes the Music bus's peak (dB) to the page twice a second, so tools/webtest.sh can
## check the music really plays (window.wandcraftMusicPeak), not just that some sound does.
var _pub_t := 0.0


func _process(dt: float) -> void:
	if not OS.has_feature("web"):
		set_process(false)
		return
	_pub_t -= dt
	if _pub_t > 0.0:
		return
	_pub_t = 0.5
	var bus := AudioServer.get_bus_index("Music")
	var db := maxf(AudioServer.get_bus_peak_volume_left_db(bus, 0), -200.0)
	JavaScriptBridge.eval("window.wandcraftMusicPeak = %.1f; window.wandcraftMusicTrack = '%s';" % [db, _track], true)
