extends Node
## Sound effects and music (sound v2: research/sound-v2.md is the cue spec, the sonic brief and
## the mix; research/sound-v2-runtime-audit.md the runtime design). Every sound is generated by
## tools/audio.sh (original, no licensed assets; assets_src/audio/LICENSES.csv lists each file).
##
## Buses, created in code (sound-v2 §6.1): 3 effects always on, 2 only while needed.
##   Master    a hard limiter at -1 dB
##   Music     a compressor keyed from Critical (ducks under threats); one low-pass, on only
##             while a snapshot closes it (menu, low HP, death). Chorus and reverb are baked.
##   SFX       combat chatter; a compressor keyed from Critical pulls it under threats
##     Glitch  -> SFX: a LOFI distortion, on only while Copy-Paste's copies of your spells play
##   Critical  -> Master, dry: hurt, telegraphs, boss moments
##   Sting     -> Master: stingers (the music ducks under them by a tween)
##   UI        menus
##   Ambience  the area bed and its spots
## Sound off mutes SFX, Critical, UI and Ambience; Music off mutes Music and Sting.
##
## One-shots: every call site asks for a cue id (and where it happened); the request waits for
## the end of the frame. flush() then merges repeats of a cue, sorts by priority, starts at most
## a budget of new voices, and steals only from voices that do not outrank the new cue. All
## per-cue behaviour is the CUES table below: call sites pass context, never a volume.
##
## Music: title | shop | cellar | grove | foundry | kernel | mini | boss. Area tracks are stems in an
## AudioStreamSynchronized (base; drums while fighting; the lead at intensity 2). Every layer
## switch lands on the next bar of the music's own sample clock.

# ------------------------------------------------------------------ the cue table

## One row per cue id: the file is res://assets/audio/sfx_<id>.wav, with variants _2, _3, ...
## (picked at random, never the same twice in a row). A field missing from a row comes from
## its group (GROUPS), then its class (CLASSES), then CUE_DEFAULT; an id with no row plays with
## the defaults, and an id with no file plays nothing (or its `fallback` cue's files).
## Fields (sound-v2 §6.2):
##   class         "crit" (Critical) | "cmb" (SFX) | "ui" (UI) | "det" (SFX, lowest)
##   prio          0-100: the budget keeps the highest; a steal takes the weakest voice that
##                 does not outrank the new cue (lowest prio, then quietest, then least left)
##   group, cap    at most `cap` voices of the group at once (the group defaults to the id)
##   gap           seconds: a repeat sooner than this is dropped
##   gain_db       added to the file's level (0: the hierarchy lives in the files, §4.1)
##   jitter_cents  random pitch +/- cents;  vol_db  random gain +/- dB
##   pan           true: panned by where it happened; false: centred
##   walk          "" | "chain" (repeats within walk_win climb the key's pentatonic, held to
##                 walk_reset, up to walk_max) | "slot" (wand slot) | "depth" (trigger depth)
##                 | "count" (pylon hits 1-4)
##   semis         a fixed pitch offset;  bus  a bus other than the class's
##   fallback      another cue whose files play while this one has none (interim)
##   fam, lufs     the loudness family of the file (§4.1: W C C+ E A M U U+) and, where the
##                 spec gives one, the cue's own target in LUFS-M (the tests check the files)
##   hook_pending  a cue with no call site yet (the tests allow it)
const CUE_DEFAULT := {"class": "cmb", "prio": 50, "group": "", "cap": 2, "gap": 0.03, "gain_db": 0.0,
	"jitter_cents": 25.0, "vol_db": 1.0, "pan": true, "walk": "", "walk_win": 0.6, "walk_reset": 0.8,
	"walk_max": 5, "semis": 0.0, "bus": "", "fallback": "", "fam": "", "lufs": 0.0, "hook_pending": false}
const CLASSES := {
	"crit": {"prio": 80, "cap": 1},
	"cmb": {},
	"ui": {"prio": 30, "cap": 3, "pan": false, "fam": "U"},
	"det": {"prio": 10, "cap": 1, "fam": "W"},
}
const GROUPS := {
	"cast": {"class": "cmb", "prio": 30, "cap": 3, "walk": "slot", "jitter_cents": 10.0, "fam": "C"},
	"hit": {"class": "cmb", "prio": 40, "cap": 4, "gap": 0.04, "fam": "C"},
	"eshot": {"class": "cmb", "prio": 60, "cap": 3, "gap": 0.06, "fam": "C+"},
	"kill": {"class": "cmb", "prio": 70, "cap": 3, "gap": 0.04, "walk": "chain", "jitter_cents": 10.0, "fam": "E"},
	"tele": {"class": "crit", "prio": 80, "cap": 3, "gap": 0.1, "jitter_cents": 0.0, "vol_db": 0.0, "fam": "A"},
}
const CUES := {
	# §4.2 casts (the CAST map below picks them; walk = the wand slot)
	"cast_spark": {"group": "cast", "gap": 0.045},
	"cast_laser": {"group": "cast", "gap": 0.05},
	"cast_needle": {"group": "cast", "gap": 0.04, "fallback": "cast_laser"},
	"cast_fan": {"group": "cast", "gap": 0.08},
	"cast_missile": {"group": "cast", "gap": 0.06},
	"cast_carry": {"group": "cast", "gap": 0.06, "fallback": "cast_spark"},
	"cast_orbit": {"group": "cast", "gap": 0.08},
	"cast_boom": {"group": "cast", "gap": 0.08},
	"cast_mine": {"group": "cast", "gap": 0.08, "fallback": "cast_boom"},
	"cast_fire": {"group": "cast", "gap": 0.05},
	"cast_wall": {"group": "cast", "gap": 0.2, "fallback": "cast_fire"},
	"cast_ice": {"group": "cast", "gap": 0.05},
	"cast_chain": {"group": "cast", "gap": 0.05},
	"cast_static": {"group": "cast", "gap": 0.05},
	"cast_arcane": {"group": "cast", "gap": 0.06},
	"cast_ping": {"group": "cast", "gap": 0.1, "fallback": "cast_arcane"},
	"cast_rot": {"group": "cast", "gap": 0.1, "fallback": "cast_arcane"},
	"cast_void": {"group": "cast", "gap": 0.1},
	"cast_summon": {"group": "cast", "gap": 0.2, "fallback": "cast_arcane"},
	"trigger": {"prio": 30, "gap": 0.06, "walk": "depth", "jitter_cents": 10.0, "fam": "C"},
	"cast_delayed": {"group": "cast", "prio": 25, "gap": 0.04, "fam": "W", "lufs": -28.0},
	"fizzle": {"prio": 45, "cap": 1, "gap": 0.2, "fam": "C"},
	"familiar_end": {"prio": 30, "cap": 1, "gap": 0.2, "fam": "C"},
	"duck_soak": {"prio": 35, "cap": 1, "gap": 0.1, "fam": "C"},
	# §4.3 hits, crits, defences
	"hit": {"group": "hit", "gap": 0.03},
	"crit": {"prio": 80, "gap": 0.05, "fam": "E"},
	"hit_heavy": {"group": "hit", "prio": 45, "gap": 0.08},
	"hit_fire": {"group": "hit"},
	"hit_ice": {"group": "hit"},
	"hit_static": {"group": "hit"},
	"hit_arcane": {"group": "hit"},
	"hit_void": {"group": "hit"},
	"hit_rot": {"group": "hit", "fallback": "hit_arcane"},
	"hit_armor": {"prio": 60, "gap": 0.05, "fam": "C+"},
	"hit_ward": {"prio": 60, "gap": 0.05, "fam": "C+"},
	"hit_shield": {"prio": 60, "gap": 0.05, "fam": "C+"},
	"armor_break": {"class": "crit", "prio": 85, "gap": 0.2, "fam": "A"},
	"shield_break": {"class": "crit", "prio": 85, "gap": 0.2, "fam": "A", "fallback": "armor_break"},
	"locked": {"prio": 55, "cap": 1, "gap": 0.25, "fam": "C+"},
	"ward_break": {"class": "crit", "prio": 85, "gap": 0.2, "fam": "A"},
	# §4.4 kills and explosions (kills share a chain walk)
	"kill": {"group": "kill"},
	"kill_mid": {"group": "kill", "prio": 75, "cap": 2, "gap": 0.05},
	"kill_big": {"class": "crit", "prio": 90, "gap": 0.1, "pan": false, "fam": "M"},
	"kill_burn": {"group": "kill", "fallback": "kill"},
	"kill_shatter": {"group": "kill", "fallback": "kill"},
	"kill_spark": {"group": "kill", "fallback": "kill"},
	"split": {"prio": 40, "cap": 1, "gap": 0.08, "fam": "C"},
	"crash": {"prio": 72, "gap": 0.05, "fam": "E"},
	"boom": {"prio": 70, "gap": 0.06, "fam": "E"},
	"bigboom": {"class": "crit", "prio": 95, "gap": 0.5, "pan": false, "fam": "M"},
	# §4.5 the player
	"hurt": {"class": "crit", "prio": 100, "gap": 0.15, "pan": false, "fam": "A", "lufs": -16.0},
	"dash": {"prio": 50, "cap": 1, "gap": 0.1, "fam": "C"},
	"mana_empty": {"prio": 55, "cap": 1, "gap": 0.5, "fam": "C+"},
	"low_hp": {"class": "crit", "prio": 60, "gap": 0.8, "pan": false, "fam": "W", "lufs": -28.0},
	"die": {"class": "crit", "prio": 100, "gap": 1.0, "pan": false, "fam": "M", "fallback": "lose"},
	"graze": {"prio": 50, "cap": 1, "gap": 0.25, "fam": "C"},
	"shield_soak": {"class": "crit", "prio": 70, "gap": 0.2, "fam": "C+"},
	"step_stone": {"class": "det", "gap": 0.18, "hook_pending": true, "lufs": -32.0},
	"step_moss": {"class": "det", "gap": 0.18, "hook_pending": true, "lufs": -32.0},
	"step_metal": {"class": "det", "gap": 0.18, "hook_pending": true, "lufs": -32.0},
	# §4.6 enemies
	"eshot": {"group": "eshot"},
	"eshot_ring": {"group": "eshot", "gap": 0.1},
	"eshot_laser": {"group": "eshot", "prio": 65, "lufs": -21.0},
	"tele": {"group": "tele"},
	"tele_charge": {"group": "tele", "fallback": "tele"},
	"tele_slam": {"group": "tele", "fallback": "tele"},
	"slam": {"class": "crit", "prio": 75, "gap": 0.1, "cap": 2, "fam": "A"},
	"fuse": {"prio": 50, "gap": 0.1, "jitter_cents": 0.0, "fam": "W", "lufs": -26.0},
	"fuse_pop": {"class": "crit", "prio": 75, "cap": 2, "gap": 0.08, "fam": "A"},
	"summon": {"prio": 55, "cap": 1, "gap": 0.3, "fam": "C+"},
	"ward_up": {"prio": 55, "cap": 1, "gap": 0.2, "fam": "C+"},
	"charge": {"prio": 65, "gap": 0.1, "fam": "C+", "lufs": -21.0},
	"bonk": {"prio": 60, "cap": 1, "gap": 0.1, "fam": "E"},
	"spawn": {"prio": 55, "cap": 1, "gap": 0.3, "fam": "C+"},
	"burn": {"class": "det", "gap": 0.15, "lufs": -30.0},
	"freeze": {"prio": 50, "gap": 0.1, "fam": "C+"},
	"panic": {"class": "crit", "prio": 85, "gap": 0.5, "fam": "A"},
	"blink_charge": {"prio": 65, "gap": 0.1, "fam": "C+"},
	"blink_land": {"prio": 60, "gap": 0.1, "fam": "C+"},
	"thorns": {"prio": 55, "cap": 1, "gap": 0.4, "fam": "C+"},
	"thorns_spark": {"group": "thorns", "prio": 55, "cap": 1, "gap": 0.4, "fam": "C+", "fallback": "thorns"},
	"box_fill": {"class": "crit", "prio": 80, "gap": 0.5, "fam": "A"},
	"trash": {"prio": 60, "cap": 1, "gap": 0.6, "fam": "C+"},
	"elite_arrive": {"class": "crit", "prio": 70, "gap": 0.5, "fam": "A"},
	"hit_proxy": {"prio": 55, "gap": 0.05, "fam": "C+"},
	"thermal": {"prio": 65, "cap": 1, "gap": 0.1, "fam": "E", "fallback": "boom"},
	# §4.7 bosses (telegraphs are 1.5 s masters played from an offset, see tele_tick)
	"tele_boss": {"group": "tele", "prio": 85, "fallback": "tele"},
	"copy_cast": {"group": "tele", "prio": 85, "gap": 0.3},
	"select_all": {"group": "tele", "prio": 85, "gap": 0.3},
	"tele_collect": {"group": "tele", "prio": 85, "gap": 0.3, "fallback": "tele"},
	"tele_lap": {"group": "tele", "prio": 85, "gap": 0.3, "fallback": "tele"},
	"tele_sweep": {"group": "tele", "prio": 85, "gap": 0.3, "fallback": "tele"},
	"ctrl_z": {"class": "crit", "prio": 85, "gap": 0.3, "fam": "A"},
	"paste": {"prio": 65, "cap": 1, "gap": 0.3, "fam": "C+"},
	"chomp": {"class": "crit", "prio": 75, "gap": 0.2, "fam": "A", "hook_pending": true},   # no longer a wind-up; a landed bite has no hook yet
	"beam": {"class": "cmb", "fam": "C+", "lufs": -21.0},                     # a loop()
	"trail_loop": {"class": "cmb", "fam": "C+"},                 # a loop()
	"derail": {"class": "crit", "prio": 90, "gap": 0.5, "pan": false, "fam": "M"},
	"roar": {"class": "crit", "prio": 95, "gap": 0.5, "pan": false, "fam": "M"},
	"phase": {"class": "crit", "prio": 95, "gap": 0.5, "pan": false, "fam": "M"},
	"key_turn": {"prio": 80, "cap": 1, "gap": 0.3, "fam": "E"},
	"weak_open": {"prio": 80, "cap": 1, "gap": 0.5, "fam": "E"},
	"gulp": {"prio": 65, "cap": 1, "gap": 0.12, "walk": "chain", "walk_win": 0.4, "walk_reset": 0.6, "walk_max": 4, "jitter_cents": 10.0, "fam": "C+"},
	"choked": {"prio": 80, "cap": 1, "gap": 0.5, "fam": "E"},
	"segment_break": {"prio": 75, "cap": 1, "gap": 0.15, "fam": "E"},
	"loop_jr": {"class": "crit", "prio": 80, "gap": 0.5, "fam": "A"},
	"back_on_track": {"class": "crit", "prio": 80, "gap": 0.5, "fam": "A"},
	# §4.8 the world
	"crate": {"prio": 50, "gap": 0.05, "walk": "chain", "walk_win": 0.25, "walk_reset": 0.25, "walk_max": 6, "jitter_cents": 10.0, "fam": "E"},
	"pod_pop": {"prio": 50, "cap": 1, "gap": 0.1, "fam": "E"},
	"bramble_burn": {"prio": 45, "cap": 1, "gap": 0.2, "fam": "E"},
	"crack_open": {"prio": 60, "cap": 1, "gap": 0.3, "fam": "E"},
	"secret": {"prio": 65, "cap": 1, "gap": 0.5, "fam": "E"},
	"pylon": {"prio": 70, "cap": 1, "gap": 0.2, "walk": "count", "jitter_cents": 0.0, "fam": "E"},
	"pit_fall": {"prio": 50, "cap": 1, "gap": 0.2, "fam": "E"},
	"chest": {"prio": 60, "cap": 1, "gap": 0.5, "fam": "E"},
	"door": {"prio": 55, "cap": 1, "gap": 0.5, "fam": "E"},
	"door_shut": {"prio": 60, "cap": 1, "gap": 0.5, "fam": "E"},
	"altar": {"class": "crit", "prio": 70, "gap": 0.5, "pan": false, "fam": "E"},
	"glitch_toll": {"class": "crit", "prio": 70, "gap": 0.5, "pan": false, "fam": "E"},
	# §4.9 rewards and progression
	"coin": {"prio": 35, "gap": 0.04, "walk": "chain", "walk_win": 0.25, "walk_reset": 0.25, "walk_max": 6, "jitter_cents": 10.0, "fam": "C"},
	"heal": {"prio": 60, "cap": 1, "gap": 0.3, "pan": false, "fam": "E"},
	"heal_small": {"class": "det", "prio": 20, "gap": 0.5, "pan": false, "lufs": -28.0},
	"heart": {"prio": 65, "cap": 1, "gap": 0.5, "pan": false, "fam": "E", "fallback": "heal"},
	"relic_proc": {"prio": 45, "cap": 1, "gap": 0.3, "fam": "C"},
	"caught": {"class": "crit", "prio": 98, "gap": 1.0, "pan": false, "fam": "M"},
	"wand_recharge": {"class": "det", "prio": 20, "gap": 0.15, "lufs": -30.0},
	# §4.10 UI
	"ui": {"class": "ui", "gap": 0.03},
	"ui_back": {"class": "ui", "gap": 0.03},
	"ui_open": {"class": "ui", "prio": 40, "gap": 0.05},
	"ui_close": {"class": "ui", "prio": 40, "gap": 0.05},
	"ui_equip": {"class": "ui", "prio": 50, "cap": 2, "gap": 0.05, "fam": "U+"},
	"ui_drag": {"class": "ui", "cap": 2, "gap": 0.05},
	"ui_drop": {"class": "ui", "prio": 40, "cap": 2, "gap": 0.05},
	"swap": {"class": "ui", "prio": 40, "cap": 2, "gap": 0.1},
	"deny": {"class": "ui", "prio": 50, "cap": 1, "gap": 0.1, "fam": "U+"},
	"buy": {"class": "ui", "prio": 50, "cap": 1, "gap": 0.1, "fam": "U+"},
	"pick": {"class": "ui", "prio": 50, "cap": 1, "gap": 0.2, "fam": "U+"},
	"levelup": {"class": "ui", "prio": 60, "cap": 1, "gap": 0.3, "fam": "M", "lufs": -18.0},
	"forge": {"class": "ui", "prio": 60, "cap": 1, "gap": 0.2, "fam": "U+"},
	"ui_confirm": {"class": "ui", "prio": 50, "cap": 1, "gap": 0.1, "fam": "U+"},
	"compile": {"class": "ui", "prio": 70, "cap": 1, "gap": 0.5, "fam": "M", "fallback": "levelup"},
	"unlock": {"class": "ui", "prio": 60, "cap": 1, "gap": 0.3, "fam": "U+", "hook_pending": true},
	"ui_pick": {"class": "ui", "cap": 2, "gap": 0.04},
	"tip": {"class": "ui", "prio": 20, "cap": 1, "gap": 1.0, "lufs": -27.0},
	"duck_say": {"class": "ui", "prio": 20, "cap": 1, "gap": 0.06, "jitter_cents": 0.0, "lufs": -26.0},
	"glitch_say": {"class": "ui", "prio": 20, "cap": 1, "gap": 0.06, "jitter_cents": 0.0, "hook_pending": true, "lufs": -26.0},
	# World 3, the Kernel (0.20, research/world3-0.20.md §3)
	"leak_drip": {"prio": 45, "cap": 2, "gap": 0.15, "fam": "C+"},
	"leak_dry": {"prio": 70, "cap": 1, "gap": 0.3, "fam": "E"},
	"null_aim": {"prio": 65, "cap": 2, "gap": 0.1, "fam": "C+"},
	"null_blink": {"prio": 60, "cap": 2, "gap": 0.1, "fam": "C+"},
	"interrupt_lock": {"class": "crit", "prio": 75, "gap": 0.3, "pan": false, "fam": "E"},
	"interrupt_free": {"prio": 65, "cap": 1, "gap": 0.3, "pan": false, "fam": "E"},
	"race_cross": {"class": "crit", "prio": 85, "gap": 0.3, "fam": "A"},
	"race_respawn": {"class": "crit", "prio": 85, "gap": 0.5, "fam": "A"},
	"diff_warn": {"class": "crit", "prio": 85, "gap": 0.3, "pan": false, "jitter_cents": 0.0, "fam": "A"},
	"diff_burn": {"class": "crit", "prio": 80, "cap": 2, "gap": 0.15, "pan": false, "fam": "A"},
	"revert_spawn": {"prio": 75, "cap": 1, "gap": 0.3, "jitter_cents": 0.0, "fam": "E"},
	"revert_take": {"class": "crit", "prio": 95, "gap": 0.5, "pan": false, "jitter_cents": 0.0, "fam": "M"},
	"glitch_unwind": {"class": "crit", "prio": 95, "gap": 0.5, "pan": false, "jitter_cents": 0.0, "fam": "M"},
	"resident_free": {"class": "ui", "prio": 70, "cap": 1, "gap": 0.5, "jitter_cents": 0.0, "fam": "M", "lufs": -18.0},
	"page_take": {"prio": 65, "cap": 1, "gap": 0.3, "pan": false, "fam": "E"},
	"skin_equip": {"class": "ui", "prio": 50, "cap": 1, "gap": 0.1, "fam": "U+"},
	"hint": {"class": "ui", "prio": 50, "cap": 1, "gap": 0.5, "fam": "U+"},
	# §4.11 ambience spots (played by the spot scheduler, on the Ambience bus)
	"amb_drip": {"class": "det", "bus": "Ambience", "lufs": -32.0},
	"amb_creak": {"class": "det", "bus": "Ambience", "lufs": -32.0},
	"amb_rustle": {"class": "det", "bus": "Ambience", "lufs": -32.0},
	"amb_glitch": {"class": "det", "bus": "Ambience", "lufs": -32.0},
	"amb_steam": {"class": "det", "bus": "Ambience", "lufs": -32.0},
	"amb_clank": {"class": "det", "bus": "Ambience", "lufs": -32.0},
	"amb_page": {"class": "det", "bus": "Ambience", "lufs": -32.0},
	"amb_tick": {"class": "det", "bus": "Ambience", "lufs": -32.0},
	"amb_nest": {"class": "det", "bus": "Ambience", "lufs": -32.0},
	"amb_spark": {"class": "det", "bus": "Ambience", "lufs": -32.0},
}
## Cues made from another cue's files: Copy-Paste's copies of your spells (your cast, 2 st
## down, through the Glitch bus, as a threat) and a familiar's shot (its cast, 6 dB down).
const DERIVED := {
	"copy:": {"class": "cmb", "prio": 60, "group": "eshot", "cap": 3, "gap": 0.06, "semis": -2.0, "bus": "Glitch", "walk": "", "fam": "C+"},
	"fam:": {"class": "cmb", "prio": 20, "group": "cast", "cap": 3, "gap": 0.08, "gain_db": -6.0, "walk": ""},
}
## Retired ids whose old files may still be on disk until tools/audio.sh regenerates.
const RETIRED := ["win", "lose", "tele_short", "tele_mid", "tele_long"]
## Voices per class and the bus each plays on. One Critical voice is kept for these cues alone.
const VOICES := {"crit": 6, "cmb": 14, "ui": 3, "det": 2}
const CLASS_BUS := {"crit": "Critical", "cmb": "SFX", "ui": "UI", "det": "SFX"}
const RESERVED := ["hurt", "die"]
## New voices started per frame at most (a cue of prio >= BUDGET_EXEMPT is never refused).
const BUDGET_WEB := 6
const BUDGET_NATIVE := 8
const BUDGET_EXEMPT := 90
## Repeats of one cue in a frame play once, the loudest, raised by 10·log10(n) dB up to this.
const MERGE_MAX_DB := 3.0
## Pitch walks (sound-v2 §6.4): the minor pentatonic in semitones, the trigger-depth steps, the
## pylon count (A C E A'), and each track's key against A (walked cues follow the music's key;
## boss C, mini E and kernel B are this file's extension of the spec's list).
const SCALE := [0, 3, 5, 7, 10, 12, 15]
const DEPTH_STEPS := [0, 7, 12]
const COUNT_STEPS := [0, 3, 7, 12]
const KEY := {"cellar": 0, "grove": 4, "foundry": -4, "kernel": 2, "title": 5, "shop": 5, "boss": 3, "mini": -5}
## Panned voices (AudioStreamPlayer2D, sound-v2 §6.2): the project's base 2D panning strength
## is 0.5, so 1.2 gives the spec's 0.6. Critical pans but is never attenuated.
const PAN_STRENGTH := 1.2
const PAN_DISTANCE := 900.0
const PAN_ATTENUATION := 0.6
## Telegraphs by attack class (sound-v2 §4.6) and by boss move (§4.7.1; others: tele_boss).
const TELE_BY_AI := {&"shoot": "tele", &"turret": "tele", &"charge": "tele_charge", &"slam": "tele_slam", &"fuse": "tele_slam"}
const TELE_BY_MOVE := {&"copy_cast": "copy_cast", &"select_all": "select_all", &"collect": "tele_collect",
	&"compact": "tele_charge", &"dump": "tele_slam", &"lap_charge": "tele_lap", &"chase": "tele_charge",
	&"sweep": "tele_sweep", &"crossfire": "tele_slam"}
## Kills that died a particular way (sound-v2 §4.4).
const KILL_BY := {&"burn": "kill_burn", &"frost": "kill_shatter", &"static": "kill_spark"}
## Enemy "shots" that are really still hazards: one cue for the whole thing, or none (a loop).
const SHOT_PREFIX := {"trail:": "", "trash:": "trash", "thorns:": "thorns", "box:": "box_fill"}
## Loops (sound-v2 §4.6, §4.7): their pan strength (a factor, as PAN_STRENGTH).
const LOOP_PAN := {"beam": 0.8, "trail_loop": 1.2}
## Ambience spots per area (sound-v2 §4.11): one every 3-9 s, panned up to 0.7 either side.
## The Kernel's two areas: the Page Archive ("kernel") and Ring Zero ("ring").
const AMB_SPOTS := {"cellar": ["amb_drip", "amb_creak"], "grove": ["amb_rustle", "amb_glitch"], "foundry": ["amb_steam", "amb_clank"],
	"kernel": ["amb_page", "amb_tick"], "ring": ["amb_nest", "amb_spark"]}

## Which cast sound each shooting spell uses (one timbre per element), and the evolved spells'
## pitch and gain on it ([semitones, dB]).
const CAST := {&"mote": "cast_spark", &"replicator": "cast_spark", &"lance": "cast_laser",
	&"needle": "cast_needle", &"exploit_needle": "cast_needle", &"fan": "cast_fan", &"moths": "cast_missile",
	&"seed": "cast_carry", &"wheel": "cast_orbit", &"disc": "cast_orbit", &"burst": "cast_boom", &"mine": "cast_mine",
	&"ember": "cast_fire", &"meltdown": "cast_fire", &"firewall": "cast_wall", &"frost": "cast_ice",
	&"absolute_zero": "cast_ice", &"spark": "cast_chain", &"storm_protocol": "cast_chain", &"static": "cast_static",
	&"hexcursor": "cast_arcane", &"ping": "cast_ping", &"bitrot": "cast_rot", &"null_orb": "cast_void",
	&"singularity": "cast_void", &"daemon": "cast_summon", &"turret": "cast_summon", &"duck": "cast_summon"}
const CAST_OFFSET := {&"replicator": [-2.0, 2.0], &"exploit_needle": [-2.0, 0.0], &"meltdown": [-3.0, 2.0],
	&"absolute_zero": [-2.0, 0.0], &"storm_protocol": [-2.0, 0.0], &"singularity": [-3.0, 0.0]}
## The hit a spell's element makes (by its cast sound); the rest hit as "hit".
const HIT := {"cast_fire": "hit_fire", "cast_wall": "hit_fire", "cast_ice": "hit_ice", "cast_static": "hit_static",
	"cast_chain": "hit_static", "cast_arcane": "hit_arcane", "cast_ping": "hit_arcane", "cast_void": "hit_void",
	"cast_rot": "hit_rot"}

## Music (sound-v2 §5): stems per track (the first always plays), the layer name of each stem,
## tempo and bar (the bar clock), and intro_s, the loop point when the intro is folded into the
## stems (whole bars; the clock phase is then just position mod bar). A stem whose file is not
## there yet is left out. Until the v2 music lands (music_boss_p3 is its marker), the boss
## plays its old separate intro through an AudioStreamInteractive, at the old tempos (V1_BPM).
const TRACKS := {
	"title": {"stems": ["music_title"], "bpm": 96.0, "beats_per_bar": 4},
	"shop": {"stems": ["music_shop"], "bpm": 96.0, "beats_per_bar": 4},
	"cellar": {"stems": ["music_cellar_base", "music_cellar_drums", "music_cellar_lead"], "layers": ["", "drums", "lead"], "bpm": 120.0, "beats_per_bar": 4},
	"grove": {"stems": ["music_grove_base", "music_grove_drums", "music_grove_lead"], "layers": ["", "drums", "lead"], "bpm": 120.0, "beats_per_bar": 4},
	"foundry": {"stems": ["music_foundry_base", "music_foundry_drums", "music_foundry_lead"], "layers": ["", "drums", "lead"], "bpm": 125.0, "beats_per_bar": 4},
	"kernel": {"stems": ["music_kernel_base", "music_kernel_drums", "music_kernel_lead"], "layers": ["", "drums", "lead"], "bpm": 100.0, "beats_per_bar": 4},
	"mini": {"stems": ["music_mini_loop", "music_mini_p2"], "layers": ["", "p2"], "bpm": 128.0, "beats_per_bar": 4, "intro_s": 3.75},
	"boss": {"stems": ["music_boss_loop", "music_boss_p2", "music_boss_p3"], "layers": ["", "p2", "p3"], "bpm": 150.0, "beats_per_bar": 4, "intro_s": 6.4,
		"v1_intro": "music_boss_intro"},
}
const V2_MUSIC_MARKER := "music_boss_p3"
const V1_BPM := {"foundry": 112.0, "boss": 128.0}
## A layer switch waits for the next bar and fades over this many seconds (negative: bars).
const LAYER_FADE := {"drums_off": -1.0}
const LAYER_FADE_DEFAULT := 0.06
const MUSIC_DB := -4.0
const LAYER_OFF_DB := -60.0
const AMB_DB := -13.0
## Stingers: which one wins the 2-voice pool, and which wait for the next beat.
const STING_PRIO := {"boss_down": 5, "victory": 4, "defeat": 4, "world": 3, "boss": 3, "glitch": 3, "reward": 2, "clear": 1}
const STING_DUCK_DB := -6.0
## Intensity steps down only after it has wanted to for this long (no flapping between waves).
const INTENSITY_HOLD := 2.0
## Low HP (sound-v2 §5.2): under this fraction a heartbeat every 1.2 -> 0.9 s, the music closes.
const LOW_HP := 0.3
## Hit-stop duck (sound-v2 §6.3): a freeze this long or longer pulls SFX down for its length.
const DUCK_MIN_T := 0.08
const DUCK_DB := -5.0
const DUCK_RELEASE := 0.08


## A cue compiled from its table row, with its files, and the request gathered this frame.
class Cue:
	var id := ""
	var cls := "cmb"
	var bus := "SFX"
	var prio := 50
	var group := ""
	var cap := 2
	var gap := 0.03
	var gain_db := 0.0
	var cents := 25.0
	var vol := 1.0
	var pan := true
	var walk := ""
	var walk_win := 0.6
	var walk_reset := 0.8
	var walk_max := 5
	var semis0 := 0.0
	var reserved := false
	var streams: Array[AudioStream] = []
	var lengths := PackedFloat32Array()
	var heavy_idx := -1     # casts: the Heavy/Empower variant (_heavy), never picked at random
	var last_pick := -1
	var last_t := -99.0     # when it last started (s)
	# this frame's request (repeats merge into it)
	var n := 0
	var at := Vector2.INF
	var db := 0.0
	var semis := 0.0
	var from := 0.0
	var force := -1


## One pool voice: a panned player (crit, cmb, det) or a centred one (ui).
class Voice:
	var p: AudioStreamPlayer
	var p2: AudioStreamPlayer2D
	var cue: Cue
	var prio := 0
	var db := 0.0
	var t0 := 0             # msec it started
	var t1 := 0             # msec it ends
	var held_left := -1     # msec left while a telegraph is held by hit-stop or a menu

	func busy(now: int) -> bool:
		return cue != null and (now < t1 or held_left >= 0)

	func stop() -> void:
		if p2:
			p2.stop()
			p2.stream_paused = false
		else:
			p.stop()
		cue = null
		t1 = 0
		held_left = -1


## The music dips under the Duck's and LINT's voices (Dialogue sets this, in dB).
var voice_db := 0.0
var sound_on := true
var music_on := true
var heartbeat_on := true
var _cues: Dictionary = {}          # id -> Cue
var _queue: Array[Cue] = []
var _later: Array[Dictionary] = []  # requests that wait a few ms (a second cast timbre, babble)
var _walks: Dictionary = {}         # group -> Vector2(step, time of the last walked request)
var _soft := ""                     # a default menu sound, dropped if the handler plays its own
var _firm_centred := false
var _pools: Dictionary = {}         # class -> Array[Voice]
var _budget := BUDGET_NATIVE
var _rng := RandomNumberGenerator.new()
var _by_prio := func(a: Cue, b: Cue) -> bool: return a.prio > b.prio or (a.prio == b.prio and a.db > b.db)
var _streams: Dictionary = {}
var _buses_built := false
var _loops: Dictionary = {}         # id -> AudioStreamPlayer2D


func _ready() -> void:
	_setup()


## Creates buses and players once (lazily too: headless test runs call sfx() before _ready).
func _setup() -> void:
	if not _pools.is_empty():
		return
	process_mode = Node.PROCESS_MODE_ALWAYS
	process_priority = 1000    # flush after everything else has asked for its sounds this frame
	_budget = BUDGET_WEB if OS.has_feature("web") else BUDGET_NATIVE
	_buses()
	for c: String in VOICES:
		var arr: Array[Voice] = []
		for i in int(VOICES[c]):
			var v := Voice.new()
			if c == "ui":
				v.p = AudioStreamPlayer.new()
				v.p.bus = CLASS_BUS[c]
				add_child(v.p)
			else:
				v.p2 = _player_2d(CLASS_BUS[c], PAN_STRENGTH, c != "crit")
				add_child(v.p2)
			arr.append(v)
		_pools[c] = arr
	_music_a = AudioStreamPlayer.new()
	_music_b = AudioStreamPlayer.new()
	for m in [_music_a, _music_b]:
		m.bus = "Music"
		m.volume_db = -80.0
		add_child(m)
	for k in 2:
		var s := AudioStreamPlayer.new()
		s.bus = "Sting"
		add_child(s)
		_stings.append(s)
		_sting_prio.append(0)
	_spot = _player_2d("Ambience", 2.0, false)
	add_child(_spot)
	Events.player_hurt.connect(func(_a: float) -> void: sfx("hurt"))
	Events.room_cleared.connect(_on_room_cleared)
	Events.boss_defeated.connect(func() -> void: sfx("bigboom"))
	apply(Game.settings())


func _player_2d(bus: String, strength: float, attenuate: bool) -> AudioStreamPlayer2D:
	var p := AudioStreamPlayer2D.new()
	p.bus = bus
	p.panning_strength = strength
	p.max_distance = PAN_DISTANCE if attenuate else 100000.0
	p.attenuation = PAN_ATTENUATION if attenuate else 0.0
	p.area_mask = 0              # no Area2D reverb lookups
	return p


## The bus layout above. Built once; a bus only sends to one before it.
func _buses() -> void:
	if _buses_built:
		return
	_buses_built = true
	_ensure_bus("SFX", "Master")
	_ensure_bus("Glitch", "SFX")
	_ensure_bus("Music", "Master")
	_ensure_bus("Critical", "Master")
	_ensure_bus("Sting", "Master")
	_ensure_bus("UI", "Master")
	_ensure_bus("Ambience", "Master")
	var master := _clear_effects("Master")
	var lim := AudioEffectHardLimiter.new()
	lim.ceiling_db = -1.0
	lim.release = 0.1
	AudioServer.add_bus_effect(master, lim)
	var music := _clear_effects("Music")
	var duck := AudioEffectCompressor.new()
	duck.sidechain = &"Critical"
	duck.threshold = -24.0
	duck.ratio = 3.0
	duck.attack_us = 5000.0
	duck.release_ms = 300.0
	AudioServer.add_bus_effect(music, duck)
	_lowpass = AudioEffectLowPassFilter.new()
	_lowpass.cutoff_hz = 20000.0
	AudioServer.add_bus_effect(music, _lowpass, 1)
	AudioServer.set_bus_effect_enabled(music, 1, false)
	var sfx_bus := _clear_effects("SFX")
	var chatter := AudioEffectCompressor.new()
	chatter.sidechain = &"Critical"
	chatter.threshold = -30.0
	chatter.ratio = 2.5
	chatter.attack_us = 2000.0
	chatter.release_ms = 180.0
	AudioServer.add_bus_effect(sfx_bus, chatter)
	var glitch := _clear_effects("Glitch")
	var lofi := AudioEffectDistortion.new()
	lofi.mode = AudioEffectDistortion.MODE_LOFI
	AudioServer.add_bus_effect(glitch, lofi, 0)
	AudioServer.set_bus_effect_enabled(glitch, 0, false)


func _ensure_bus(name: String, send: String) -> void:
	var i := AudioServer.get_bus_index(name)
	if i < 0:
		AudioServer.add_bus()
		i = AudioServer.bus_count - 1
		AudioServer.set_bus_name(i, name)
	AudioServer.set_bus_send(i, send)


func _clear_effects(name: String) -> int:
	var i := AudioServer.get_bus_index(name)
	while AudioServer.get_bus_effect_count(i) > 0:
		AudioServer.remove_bus_effect(i, 0)
	return i


## The bus effects that are running now (the web-cost DOG: at most 3 when nothing special is on).
func active_effects() -> int:
	var n := 0
	for b in AudioServer.bus_count:
		for e in AudioServer.get_bus_effect_count(b):
			if AudioServer.is_bus_effect_enabled(b, e):
				n += 1
	return n


func apply(settings: Dictionary) -> void:
	# Game applies saved settings before this node's _ready: make sure the buses exist
	_buses()
	sound_on = bool(settings.get("sound", true))
	music_on = bool(settings.get("music", true))
	heartbeat_on = bool(settings.get("heartbeat", true))
	for b in ["SFX", "Critical", "UI", "Ambience"]:
		AudioServer.set_bus_mute(AudioServer.get_bus_index(b), not sound_on)
	for b in ["Music", "Sting"]:
		AudioServer.set_bus_mute(AudioServer.get_bus_index(b), not music_on)
	if not sound_on:
		_stop_voices(["crit", "cmb", "ui", "det"])
		_later.clear()
		for id: String in _loops:
			(_loops[id] as AudioStreamPlayer2D).stop()
	if not music_on:
		for s: AudioStreamPlayer in _stings:
			s.stop()


# ------------------------------------------------------------------ one-shots

## Asks for a sound effect. `at` is where it happened in the world (it pans); `gain_db` is added
## to the cue's own gain (context only, such as a second timbre); `step` is the walk index for
## "slot", "depth" and "count" cues.
func sfx(id: String, at := Vector2.INF, gain_db := 0.0, step := 0) -> void:
	_request(id, at, gain_db, step, 0.0, 0.0, -1)


## A default menu sound (a button press, a screen opening or closing). It plays only if nothing
## else centred was asked for in the same frame, and only the first of them per frame.
func ui(id: String) -> void:
	if not sound_on or Game.quiet > 0:
		return
	if _soft == "":
		_soft = id


## The cast sound of a spell id.
static func cast_name(spell_id: StringName) -> String:
	return CAST.get(spell_id, "cast_spark")


## A wand cast (sound-v2 §4.2): the first spell's timbre, walked by its wand slot, raised by
## 2·log2(spells) dB (at most 3); a second, different timbre 20 ms later at -4 dB; the "heavy"
## variant when the cast carries Heavy or Empower.
func cast_plan(spell_ids: Array[StringName], at: Vector2, slot: int, heavy := false) -> void:
	if spell_ids.is_empty() or not sound_on or Game.quiet > 0:
		return
	var first := spell_ids[0]
	var name := cast_name(first)
	var off: Array = CAST_OFFSET.get(first, [0.0, 0.0])
	var gain := minf(3.0, 2.0 * log(float(spell_ids.size())) / log(2.0)) + float(off[1])
	var c := _cue(name)
	_request(name, at, gain, slot, float(off[0]), 0.0, c.heavy_idx if heavy else -1)
	for id in spell_ids:
		var second := cast_name(id)
		if second != name:
			var off2: Array = CAST_OFFSET.get(id, [0.0, 0.0])
			_later.append({"ms": Time.get_ticks_msec() + 20, "id": second, "at": at, "db": -4.0 + float(off2[1]),
				"step": slot, "semis": float(off2[0])})
			break


## One spell's cast sound (a copy or a familiar asks through its own cue; see DERIVED).
func cast(spell_id: StringName, at := Vector2.INF, slot := 0) -> void:
	var ids: Array[StringName] = [spell_id]
	cast_plan(ids, at, slot)


## A familiar fires (sound-v2 §4.2 familiar_shot): its payload's cast, 6 dB down.
func familiar_shot(spell_id: StringName, at: Vector2) -> void:
	_request("fam:" + cast_name(spell_id), at, 0.0, 0, 0.0, 0.0, -1)


## A hit on an enemy: the element's hit, with the crit and the heavy body as sweeteners on it.
func hit(id: String, at: Vector2, crit: bool, heavy: bool) -> void:
	_request(id, at, 0.0, 0, 0.0, 0.0, -1)
	if crit:
		_request("crit", at, 0.0, 0, 0.0, 0.0, -1)
	if heavy:
		_request("hit_heavy", at, 0.0, 0, 0.0, 0.0, -1)


## An enemy dies: size 0 fodder, 1 heavy, 2 elite; `how` (&"burn" | &"frost" | &"static") picks
## the way it died, for fodder.
func kill(_kind: StringName, at: Vector2, size: int, how := &"") -> void:
	var id := "kill_big" if size >= 2 else ("kill_mid" if size == 1 else String(KILL_BY.get(how, "kill")))
	_request(id, at, 0.0, 0, 0.0, 0.0, -1)


## An enemy shot leaves: `sound` from the shooter, `by` its source tag. Still hazards get one
## cue for the whole thing (thorns, trash, a box fill) or none; your copied spells sound like
## your spells, glitched.
func enemy_shot(sound: String, by: String, at: Vector2) -> void:
	if by.begins_with("copy:"):
		_request("copy:" + cast_name(StringName(by.substr(5))), at, 0.0, 0, 0.0, 0.0, -1)
		return
	for pre: String in SHOT_PREFIX:
		if by.begins_with(pre):
			var id: String = SHOT_PREFIX[pre]
			if id != "":
				_request("thorns_spark" if id == "thorns" and by.ends_with("spark_plug") else id, at, 0.0, 0, 0.0, 0.0, -1)
			return
	_request(sound, at, 0.0, 0, 0.0, 0.0, -1)


## The hit sound a spell's element makes.
static func hit_for(spell_id: StringName) -> String:
	var h: Variant = _hit_cache.get(spell_id)
	if h == null:
		h = HIT.get(CAST.get(spell_id, ""), "hit")
		_hit_cache[spell_id] = h
	return h


static var _hit_cache := {}


## The hit a bullet makes: its coat's element when it has one (rot > static > chill > burn,
## the rarer mechanic announced), else its spell's.
static func hit_for_bullet(spell_id: StringName, burn: int, chill: int, static_on: bool, rot: int) -> String:
	if rot > 0:
		return "hit_rot"
	if static_on:
		return "hit_static"
	if chill > 0:
		return "hit_ice"
	if burn > 0:
		return "hit_fire"
	return hit_for(spell_id)


## A telegraph that ends on the frame its attack releases (sound-v2 §4.6, §4.7.1): call it every
## tick of the wind-up with the time left now and a tick ago (INF on the first tick). The cue
## starts once no more than its file's length is left, from the offset that makes it end when
## the time runs out. World time, so a hit-stop or a menu holds it too.
func tele_tick(id: String, left: float, prev_left: float, at: Vector2) -> void:
	var off := tele_offset(id, left, prev_left)
	if off >= 0.0:
		_request(id, at, 0.0, 0, 0.0, off, -1)


## Where in its file a telegraph starts this tick (-1: not this tick).
func tele_offset(id: String, left: float, prev_left: float) -> float:
	var c := _cue(id)
	if c.streams.is_empty() or left < 0.0:
		return -1.0
	var ln := c.lengths[0]
	if prev_left > ln and left <= ln:
		return ln - left
	return -1.0


static func tele_for_ai(ai: StringName, panicked := false) -> String:
	return "tele_charge" if panicked else String(TELE_BY_AI.get(ai, "tele"))


static func tele_for_move(move: StringName) -> String:
	return String(TELE_BY_MOVE.get(move, "tele_boss"))


## The Duck talks (sound-v2 §4.10): one babble syllable per 2-3 characters of the line.
func babble(text: String, who := "duck") -> void:
	if not sound_on or Game.quiet > 0:
		return
	var n := clampi(roundi(text.length() / 2.5), 1, 24)
	var now := Time.get_ticks_msec()
	var id := "glitch_say" if who != "duck" else "duck_say"
	for k in n:
		_later.append({"ms": now + k * 80, "id": id, "at": Vector2.INF, "db": 0.0, "step": 0,
			"semis": 0.0 if who != "duck" else _rng.randf_range(-2.0, 2.0)})


## The voice class of a cue ("crit" | "cmb" | "ui" | "det").
static func voice_class(id: String) -> String:
	return String(_row(id)["class"])


## A cue's full row: its table row over its group, its class and the defaults.
static func _row(id: String) -> Dictionary:
	var row: Dictionary = CUES.get(id, {})
	for pre: String in DERIVED:
		if id.begins_with(pre):
			row = DERIVED[pre]
	var grp: Dictionary = GROUPS.get(String(row.get("group", "")), {})
	var cls := String(row.get("class", grp.get("class", "cmb")))
	return CUE_DEFAULT.merged(CLASSES.get(cls, {}), true).merged(grp, true).merged(row, true).merged({"class": cls}, true)


func _request(id: String, at: Vector2, gain_db: float, step: int, semis: float, from: float, force: int) -> void:
	if not sound_on or Game.quiet > 0:
		return
	var c: Cue = _cues.get(id)
	if c == null:
		c = _cue(id)
	if c.walk != "":
		semis += _walk(c, step)
	if c.n == 0:
		_queue.append(c)
		c.at = at
		c.db = gain_db
		c.semis = semis
		c.from = from
		c.force = force
	else:
		if gain_db > c.db:
			c.db = gain_db
			c.at = at
		c.semis = maxf(c.semis, semis)
	c.n += 1
	if at == Vector2.INF:
		_firm_centred = true


## The walk's pitch in semitones for this request.
func _walk(c: Cue, step: int) -> float:
	var key := float(KEY.get(_track, 0))
	match c.walk:
		"chain":
			var t := Time.get_ticks_msec() / 1000.0
			var w: Vector2 = _walks.get(c.group, Vector2(-1.0, -99.0))
			var k := 0
			if t - w.y <= c.walk_win:
				k = mini(int(w.x) + 1, c.walk_max)
			elif t - w.y <= c.walk_reset:
				k = maxi(0, int(w.x))
			_walks[c.group] = Vector2(k, t)
			return key + float(SCALE[mini(k, SCALE.size() - 1)])
		"slot":
			return key + float(SCALE[posmod(step, 5)])
		"depth":
			return key + float(DEPTH_STEPS[clampi(step, 0, DEPTH_STEPS.size() - 1)])
		"count":
			return key + float(COUNT_STEPS[posmod(step, COUNT_STEPS.size())])
	return 0.0


## Compiles a cue from its row (and loads its files) the first time it is asked for.
func _cue(id: String) -> Cue:
	var c: Cue = _cues.get(id)
	if c:
		return c
	c = Cue.new()
	c.id = id
	var d := _row(id)
	c.cls = String(d["class"]) if VOICES.has(String(d["class"])) else "cmb"
	c.bus = String(d["bus"]) if String(d["bus"]) != "" else String(CLASS_BUS[c.cls])
	c.prio = int(d["prio"])
	c.group = String(d["group"]) if String(d["group"]) != "" else id
	c.cap = maxi(1, int(d["cap"]))
	c.gap = float(d["gap"])
	c.gain_db = float(d["gain_db"])
	c.cents = float(d["jitter_cents"])
	c.vol = float(d["vol_db"])
	c.pan = bool(d["pan"])
	c.walk = String(d["walk"])
	c.walk_win = float(d["walk_win"])
	c.walk_reset = float(d["walk_reset"])
	c.walk_max = int(d["walk_max"])
	c.semis0 = float(d["semis"])
	c.reserved = id in RESERVED
	var file := id
	for pre: String in DERIVED:
		if id.begins_with(pre):
			file = id.substr(pre.length())
	_load_files(c, file)
	if c.streams.is_empty() and String(d["fallback"]) != "":
		var fb := _cue(String(d["fallback"]))
		c.streams = fb.streams
		c.lengths = fb.lengths
		c.heavy_idx = fb.heavy_idx
	_cues[id] = c
	return c


func _load_files(c: Cue, file: String) -> void:
	var path := "res://assets/audio/sfx_%s.wav" % file
	var k := 1
	while ResourceLoader.exists(path):
		var s: AudioStream = load(path)
		if s:
			c.streams.append(s)
			c.lengths.append(s.get_length())
		k += 1
		path = "res://assets/audio/sfx_%s_%d.wav" % [file, k]
	# a cast's Heavy/Empower variant (sfx_<id>_heavy.wav) goes last and is never picked at random
	path = "res://assets/audio/sfx_%s_heavy.wav" % file
	if c.group == "cast" and ResourceLoader.exists(path) and not c.streams.is_empty():
		var h: AudioStream = load(path)
		if h:
			c.heavy_idx = c.streams.size()
			c.streams.append(h)
			c.lengths.append(h.get_length())


## Starts this frame's sounds: repeats merged, highest priority first, at most the budget of
## new voices (moments are never refused). Returns how many started. Called once a frame.
func flush() -> int:
	if not _later.is_empty():
		var ms := Time.get_ticks_msec()
		var i := 0
		while i < _later.size():
			var r: Dictionary = _later[i]
			if int(r["ms"]) <= ms:
				_later.remove_at(i)
				_request(r["id"], r["at"], r["db"], r["step"], r["semis"], 0.0, -1)
			else:
				i += 1
	if _soft != "":
		if not _firm_centred:
			_request(_soft, Vector2.INF, 0.0, 0, 0.0, 0.0, -1)
		_soft = ""
	_firm_centred = false
	if _queue.is_empty():
		return 0
	_setup()
	var now := Time.get_ticks_msec()
	var t := now / 1000.0
	if _queue.size() > 1:
		_queue.sort_custom(_by_prio)
	var ear := _ear()
	var live := is_inside_tree()   # headless tests run before the tree is up: bookkeeping only
	var started := 0
	for c in _queue:
		var n := c.n
		c.n = 0
		if c.streams.is_empty() or t - c.last_t < c.gap:
			continue
		if started >= _budget and c.prio < BUDGET_EXEMPT:
			continue
		var v := _voice_for(c, now)
		if v == null:
			continue
		c.last_t = t
		_start(v, c, n, now, ear, live)
		started += 1
	_queue.clear()
	return started


## A voice for the cue. Its group at its cap: the group's weakest voice. Else a free voice; else
## the weakest voice that does not outrank it (lowest prio, then quietest, then least time
## left); else none. The last Critical voice is only for the RESERVED cues.
func _voice_for(c: Cue, now: int) -> Voice:
	var pool: Array[Voice] = _pools[c.cls]
	var n := pool.size() - (1 if c.cls == "crit" and not c.reserved else 0)
	var in_group := 0
	var weakest: Voice = null
	for i in n:
		var v := pool[i]
		if v.busy(now) and v.cue.group == c.group:
			in_group += 1
			if weakest == null or _weaker(v, weakest):
				weakest = v
	if in_group >= c.cap:
		return weakest
	var victim: Voice = null
	for i in n:
		var v := pool[i]
		if not v.busy(now):
			return v
		if v.prio <= c.prio and (victim == null or _weaker(v, victim)):
			victim = v
	return victim


static func _weaker(a: Voice, b: Voice) -> bool:
	if a.prio != b.prio:
		return a.prio < b.prio
	if absf(a.db - b.db) > 0.5:
		return a.db < b.db
	return a.t1 < b.t1


func _start(v: Voice, c: Cue, n: int, now: int, ear: Vector2, live := true) -> void:
	var k := c.force if c.force >= 0 and c.force < c.streams.size() else _pick(c)
	var cents := _rng.randf_range(-c.cents, c.cents) if c.cents > 0.0 else 0.0
	var pitch := pow(2.0, (c.semis0 + c.semis + cents / 100.0) / 12.0)
	var db := c.gain_db + c.db + minf(MERGE_MAX_DB, 10.0 * log(float(n)) / log(10.0))
	if c.vol > 0.0:
		db += _rng.randf_range(-c.vol, c.vol)
	var from := clampf(c.from, 0.0, c.lengths[k])
	if v.cue:
		v.stop()
	v.cue = c
	v.prio = c.prio
	v.db = db
	v.t0 = now
	v.t1 = now + int((c.lengths[k] - from) / pitch * 1000.0) + 20
	if not live:
		return
	if v.p2:
		v.p2.stream = c.streams[k]
		v.p2.bus = c.bus
		v.p2.global_position = c.at if c.pan and c.at != Vector2.INF else ear
		v.p2.pitch_scale = pitch
		v.p2.volume_db = db
		v.p2.play(from)
	else:
		v.p.stream = c.streams[k]
		v.p.volume_db = db
		v.p.pitch_scale = pitch
		v.p.play(from)
		v.p.pitch_scale = pitch   # godot #95850 (web): set it again once playing
	if c.bus == "Glitch":
		_glitch_until = maxi(_glitch_until, v.t1)


## A variant, never the one that played last (and never a cast's Heavy variant at random).
func _pick(c: Cue) -> int:
	var n := c.streams.size() - (1 if c.heavy_idx >= 0 else 0)
	if n <= 1:
		return 0
	var k := _rng.randi_range(0, n - 1) if c.last_pick < 0 or c.last_pick >= n else _rng.randi_range(0, n - 2)
	if c.last_pick >= 0 and c.last_pick < n and k >= c.last_pick:
		k += 1
	c.last_pick = k
	return k


## Where the listener is: the middle of the screen, in world coordinates.
func _ear() -> Vector2:
	var vp := get_viewport()
	if vp == null:
		return Vector2.ZERO
	return (vp.get_global_canvas_transform() * vp.get_canvas_transform()).affine_inverse() * (vp.get_visible_rect().size * 0.5)


func _stop_voices(classes: Array) -> void:
	for c: String in classes:
		if _pools.has(c):
			for v: Voice in _pools[c]:
				if v.cue:
					v.stop()


## A room change: world sounds, loops and anything still waiting stop (the UI keeps playing).
func stop_world() -> void:
	for c in _queue:
		c.n = 0
	_queue.clear()
	_later.assign(_later.filter(func(r: Dictionary) -> bool: return String(r["id"]).ends_with("_say")))
	_stop_voices(["crit", "cmb", "det"])
	loops_off()
	_tele_hold_until = 0


## Tests: forget every gap, walk and voice.
func reset() -> void:
	stop_world()
	_stop_voices(["ui"])
	_later.clear()
	_walks.clear()
	_soft = ""
	_firm_centred = false
	for id: String in _cues:
		var c: Cue = _cues[id]
		c.last_t = -99.0
		c.last_pick = -1


## The cue ids of a class's voices playing now (tests).
func voices_busy(cls: String) -> Array[String]:
	var out: Array[String] = []
	var now := Time.get_ticks_msec()
	for v: Voice in _pools.get(cls, []):
		if v.busy(now):
			out.append(v.cue.id)
	return out


## A world loop (the Deadlock beam, the Loop's trail): on starts or moves it, off stops it.
## `pitch` (the beam turns faster in phase 2) is set after play() (godot #95850).
func loop(id: String, on: bool, at := Vector2.INF, pitch := 1.0) -> void:
	var p: AudioStreamPlayer2D = _loops.get(id)
	if not on:
		if p and p.playing:
			p.stop()
		return
	if not sound_on or Game.quiet > 0 or not is_inside_tree():
		return
	if p == null:
		var c := _cue(id)
		if c.streams.is_empty():
			return
		var s := c.streams[0]
		if s is AudioStreamWAV and (s as AudioStreamWAV).loop_mode == AudioStreamWAV.LOOP_DISABLED:
			var w := (s as AudioStreamWAV).duplicate() as AudioStreamWAV
			w.loop_mode = AudioStreamWAV.LOOP_FORWARD
			w.loop_begin = 0
			w.loop_end = int(w.get_length() * w.mix_rate)
			s = w
		p = _player_2d(c.bus, float(LOOP_PAN.get(id, PAN_STRENGTH)), false)
		p.stream = s
		p.volume_db = c.gain_db
		add_child(p)
		_loops[id] = p
	p.global_position = at if at != Vector2.INF else _ear()
	if not p.playing:
		p.play()
	if p.pitch_scale != pitch:
		p.pitch_scale = pitch


func loops_off() -> void:
	for id: String in _loops:
		(_loops[id] as AudioStreamPlayer2D).stop()


func loop_playing(id: String) -> bool:
	return _loops.has(id) and (_loops[id] as AudioStreamPlayer2D).playing


# ------------------------------------------------------------------ state: snapshots, low HP, hit-stop

var _snap := &"play"
var _low := false
var _lowpass: AudioEffectLowPassFilter
var _lp_hz := 20000.0
var _snap_music_db := 0.0
var _snap_amb_db := 0.0
var _snap_tw: Tween
var _applied := Vector4(-1.0, -1.0, -1.0, -1.0)   # low-pass, music, ambience, SFX last written
var _hp_frac := 1.0
var _hp_seen := -99999
var _hb_t := 0.0
var _duck_until := 0
var _duck_db := 0.0
var _tele_hold_until := 0
var _tele_held := false
var _glitch_until := 0
var _glitch_on := false


## The mix state (sound-v2 §5.2): &"play" | &"menu" (also &"pause", &"editor", &"map",
## &"reward", &"shop") | &"dead".
##   menu  the music closes to 1.2 kHz and drops 4 dB, the ambience 8 dB; telegraphs hold
##   dead  the music sinks behind a closing low-pass for about a second (design-plan §10)
##   play  all off (low HP closes the music to 3 kHz and 2 dB on top of it)
func snapshot(name: StringName) -> void:
	if Game.quiet > 0:
		return
	if name in [&"pause", &"editor", &"map", &"reward", &"shop"]:
		name = &"menu"
	if name == _snap:
		return
	_snap = name
	_retarget()


func current_snapshot() -> StringName:
	return _snap


## Kept for callers of v1: the death sweep is the "dead" snapshot.
func death_sweep() -> void:
	snapshot(&"dead")


## The low-pass, music and ambience levels the snapshot (and low HP) want, tweened there.
func _retarget() -> void:
	var lp := 20000.0
	var mdb := 0.0
	var adb := 0.0
	var t := 0.4
	match _snap:
		&"menu":
			lp = 1200.0
			mdb = -4.0
			adb = -8.0
			t = 0.25
		&"dead":
			lp = 500.0
			adb = -12.0
			t = 1.0
			_lp_hz = minf(_lp_hz, 16000.0)
		_:
			if _low:
				lp = 3000.0
				mdb = -2.0
	if _snap_tw:
		_snap_tw.kill()
	if not is_inside_tree():
		_lp_hz = lp
		_snap_music_db = mdb
		_snap_amb_db = adb
		return
	_snap_tw = create_tween().set_parallel(true)
	var lpt := _snap_tw.tween_property(self, "_lp_hz", lp, t)
	if _snap == &"dead":
		lpt.set_ease(Tween.EASE_OUT).set_trans(Tween.TRANS_EXPO)
	_snap_tw.tween_property(self, "_snap_music_db", mdb, t)
	_snap_tw.tween_property(self, "_snap_amb_db", adb, t)


## The player's HP as a fraction, every tick of play. Under LOW_HP a heartbeat plays and the
## music closes a little; it lifts a moment after the calls stop (a menu, death, the title).
func player_hp(frac: float) -> void:
	if Game.quiet > 0:
		return
	_hp_frac = frac
	_hp_seen = Time.get_ticks_msec()


func low_hp_active() -> bool:
	return _low


## World hit-stop: telegraphs hold for its length (so they still end on release), and one of
## DUCK_MIN_T or longer pulls the SFX bus down so the impact lands in a gap (sound-v2 §6.3).
func on_hitstop(t: float) -> void:
	if Game.quiet > 0:
		return
	var until := Time.get_ticks_msec() + int(t * 1000.0)
	_tele_hold_until = maxi(_tele_hold_until, until)
	if t >= DUCK_MIN_T:
		_duck_until = maxi(_duck_until, until)


func _update_state(dt: float) -> void:
	var now := Time.get_ticks_msec()
	# low HP: the heartbeat and the music's filter
	var low := heartbeat_on and sound_on and _snap == &"play" and _hp_frac < LOW_HP and now - _hp_seen < 300
	if low != _low:
		_low = low
		_retarget()
		_hb_t = 0.0
	if _low:
		_hb_t -= dt
		if _hb_t <= 0.0:
			_hb_t = lerpf(0.9, 1.2, clampf(_hp_frac / LOW_HP, 0.0, 1.0))
			_request("low_hp", Vector2.INF, 0.0, 0, 0.0, 0.0, -1)
	# telegraphs hold while the world does (hit-stop, a menu over play)
	var hold := _snap == &"menu" or now < _tele_hold_until
	if hold != _tele_held:
		_tele_held = hold
		for v: Voice in _pools.get("crit", []):
			if v.cue and v.cue.group == "tele" and v.busy(now):
				v.p2.stream_paused = hold
				if hold:
					v.held_left = maxi(0, v.t1 - now)
				else:
					v.t1 = now + v.held_left
					v.held_left = -1
	# the hit-stop duck: down at once, back over DUCK_RELEASE
	var want := DUCK_DB if now < _duck_until else 0.0
	_duck_db = want if want < _duck_db else move_toward(_duck_db, 0.0, -DUCK_DB * dt / DUCK_RELEASE)
	# the stinger duck: down over 80 ms, back over 0.4 s
	var sw := STING_DUCK_DB if now < _sting_until else 0.0
	_sting_db = move_toward(_sting_db, sw, (-STING_DUCK_DB / 0.08 if sw < _sting_db else -STING_DUCK_DB / 0.4) * dt)
	# the Glitch bus's distortion runs only while a copied spell plays
	var g := now < _glitch_until
	if g != _glitch_on:
		_glitch_on = g
		AudioServer.set_bus_effect_enabled(AudioServer.get_bus_index("Glitch"), 0, g)
	# the snapshot's values, written only when they change
	var cur := Vector4(_lp_hz, _snap_music_db + _sting_db + voice_db, _snap_amb_db, _duck_db)
	if cur != _applied:
		_applied = cur
		var mb := AudioServer.get_bus_index("Music")
		_lowpass.cutoff_hz = _lp_hz
		AudioServer.set_bus_effect_enabled(mb, 1, _lp_hz < 18000.0)
		AudioServer.set_bus_volume_db(mb, cur.y)
		AudioServer.set_bus_volume_db(AudioServer.get_bus_index("Ambience"), _snap_amb_db)
		AudioServer.set_bus_volume_db(AudioServer.get_bus_index("SFX"), _duck_db)


# ------------------------------------------------------------------ stingers and ambience

var _stings: Array[AudioStreamPlayer] = []
var _sting_prio: Array[int] = []
var _sting_until := 0
var _sting_db := 0.0
var _last_sting := ""
var _last_sting_ms := -99999


## A stinger (clear, reward, boss, boss_down, world, victory, defeat, glitch) on the Sting bus;
## the music ducks 6 dB under it. The area's own version plays when there is one
## (sting_clear_grove): the current track's, or `track`'s when given (sting("world", false,
## "kernel") before the Kernel's music starts). `quantize` lands it on the music's next beat.
## Two voices, by STING_PRIO.
func sting(name: String, quantize := false, track := "") -> void:
	if not music_on or Game.quiet > 0 or not is_inside_tree():
		return
	_setup()
	var tk := track if track != "" else _track
	var s := stream("sting_%s_%s" % [name, tk]) if tk != "" else null
	if s == null:
		s = stream("sting_" + name)
	if s == null:
		return
	var prio := int(STING_PRIO.get(name, 1))
	var k := 0 if not _stings[0].playing else (1 if not _stings[1].playing else (0 if _sting_prio[0] <= _sting_prio[1] else 1))
	if _stings[k].playing and _sting_prio[k] > prio:
		return
	var p := _stings[k]
	_sting_prio[k] = prio
	p.stream = s
	_last_sting = name
	_last_sting_ms = Time.get_ticks_msec()
	var wait := float(bar_clock().get("to_next_beat", 0.0)) if quantize else 0.0
	_sting_until = Time.get_ticks_msec() + int((wait + s.get_length()) * 1000.0)
	if wait > 0.03:
		create_tween().tween_callback(p.play).set_delay(wait)
	else:
		p.play()


func _on_room_cleared() -> void:
	# a boss room's clear is its boss_down stinger (world asks for it just before)
	if _last_sting == "boss_down" and Time.get_ticks_msec() - _last_sting_ms < 1500:
		return
	sting("clear", true)


## The area's ambience bed (cellar | grove | foundry | kernel | ring, "" for none), a quiet loop on
## its own bus under the music, with spots now and then. Crossfades like the music.
var _amb: AudioStreamPlayer
var _amb_name := ""
var _amb_tw: Tween
var _spot: AudioStreamPlayer2D
var _spot_t := 4.0


func ambience(area: String, fade := 1.2) -> void:
	if area == _amb_name or Game.quiet > 0 or not is_inside_tree():
		return
	_amb_name = area
	if _amb == null:
		_amb = AudioStreamPlayer.new()
		_amb.bus = "Ambience"
		add_child(_amb)
	if _amb_tw:
		_amb_tw.kill()
	_amb_tw = create_tween()
	if area == "":
		_amb_tw.tween_property(_amb, "volume_db", -80.0, fade)
		_amb_tw.tween_callback(_amb.stop)
		return
	var s := stream("music_amb_" + area)
	if s == null:
		return
	_amb.stream = s
	_amb.volume_db = -60.0
	_amb.play()
	_amb_tw.tween_property(_amb, "volume_db", AMB_DB, fade)


func ambience_name() -> String:
	return _amb_name


func _update_spots(dt: float) -> void:
	if _amb_name == "" or not sound_on or not AMB_SPOTS.has(_amb_name):
		return
	_spot_t -= dt
	if _spot_t > 0.0:
		return
	_spot_t = _rng.randf_range(3.0, 9.0)
	var ids: Array = AMB_SPOTS[_amb_name]
	var c := _cue(String(ids[_rng.randi() % ids.size()]))
	if c.streams.is_empty():
		return
	var half := get_viewport().get_visible_rect().size.x * 0.5 if get_viewport() else 240.0
	_spot.stream = c.streams[_pick(c)]
	_spot.global_position = _ear() + Vector2(_rng.randf_range(-0.7, 0.7) * half, 0.0)
	_spot.play()


# ------------------------------------------------------------------ music

var _music_a: AudioStreamPlayer
var _music_b: AudioStreamPlayer
var _cur: AudioStreamPlayer        # the player carrying the current track (null: silence)
var _track := ""
var _tween: Tween
var _t_acc := 0.0                  # the clock of a v1 intro track (its player cannot report it)
var _layers: Dictionary = {}       # layer name -> [AudioStreamSynchronized, index]
var _layer_on: Dictionary = {}
var _layer_tw: Dictionary = {}
var _layer_at: Dictionary = {}     # layer name -> the music position its last switch lands on
var _built: Dictionary = {}        # track -> AudioStream
var _built_layers: Dictionary = {} # track -> {layer name: stem index}
var _int := 0
var _int_want := 0
var _int_low_t := 0.0


## A plain file from res://assets/audio (cached; null when missing).
func stream(name: String) -> AudioStream:
	if not _streams.has(name):
		var path := "res://assets/audio/%s.wav" % name
		_streams[name] = load(path) if ResourceLoader.exists(path) else null
	return _streams[name]


static func has_track(track: String) -> bool:
	return TRACKS.has(track)


## True when a track's first stem is on disk (the mini track waits for its files).
static func track_ready(track: String) -> bool:
	return TRACKS.has(track) and ResourceLoader.exists("res://assets/audio/%s.wav" % TRACKS[track]["stems"][0])


static func music_v2() -> bool:
	return ResourceLoader.exists("res://assets/audio/%s.wav" % V2_MUSIC_MARKER)


## A track's tempo: the spec's, or the old one until the v2 music lands.
static func track_bpm(track: String) -> float:
	if not music_v2() and V1_BPM.has(track):
		return float(V1_BPM[track])
	return float((TRACKS[track] as Dictionary).get("bpm", 120.0))


## The stream for a track, built once: a single loop, or a synchronized set of the stems that
## exist (the v1 boss: its old intro handing over to that set).
func track_stream(track: String) -> AudioStream:
	if _built.has(track):
		return _built[track]
	var def: Dictionary = TRACKS[track]
	var stems: Array = def["stems"]
	var names: Array = def.get("layers", [])
	var have: Array[AudioStream] = []
	var map := {}
	for i in stems.size():
		var st := stream(stems[i])
		if st:
			if i < names.size() and names[i] != "":
				map[names[i]] = have.size()
			have.append(st)
	var s: AudioStream = null
	if have.size() == 1 and names.is_empty():
		s = have[0]
	elif not have.is_empty():
		var sync := AudioStreamSynchronized.new()
		sync.stream_count = have.size()
		for i in have.size():
			sync.set_sync_stream(i, have[i])
			sync.set_sync_stream_volume(i, 0.0 if i == 0 else LAYER_OFF_DB)
		s = sync
		if def.has("v1_intro") and not music_v2() and stream(def["v1_intro"]) != null:
			var inter := AudioStreamInteractive.new()
			inter.clip_count = 2
			inter.set_clip_name(0, &"intro")
			inter.set_clip_stream(0, stream(def["v1_intro"]))
			inter.set_clip_auto_advance(0, AudioStreamInteractive.AUTO_ADVANCE_ENABLED)
			inter.set_clip_auto_advance_next_clip(0, 1)
			inter.set_clip_name(1, &"loop")
			inter.set_clip_stream(1, sync)
			inter.initial_clip = 0
			s = inter
	_built[track] = s
	_built_layers[track] = map
	return s


## Crossfades to a music track: title | shop | cellar | grove | foundry | kernel | mini | boss | ""
## (silence). The same track keeps playing (a new room of the same area does not restart it).
## Every optional layer starts off. The title and silence also fade the ambience out.
func music(track: String, fade := 0.8) -> void:
	if track == "" or track == "title":
		ambience("", fade)
	if track == _track:
		return
	_setup()
	_track = track
	for k: String in _layer_tw:
		var old: Tween = _layer_tw[k]
		if old:
			old.kill()
	_layer_tw.clear()
	_layers.clear()
	_layer_on.clear()
	_layer_at.clear()
	_int = 0
	_int_want = 0
	_int_low_t = 0.0
	var s: AudioStream = track_stream(track) if TRACKS.has(track) else null
	if s:
		# the layer bookkeeping does not need a running tree (the tests check it headless)
		var sync: AudioStreamSynchronized = s if s is AudioStreamSynchronized else (
			(s as AudioStreamInteractive).get_clip_stream(1) if s is AudioStreamInteractive else null)
		if sync:
			for i in sync.stream_count:
				sync.set_sync_stream_volume(i, 0.0 if i == 0 else LAYER_OFF_DB)
			var map: Dictionary = _built_layers.get(track, {})
			for name: String in map:
				_layers[name] = [sync, int(map[name])]
	if not is_inside_tree():
		return
	var incoming := _music_b if _cur == _music_a else _music_a
	if _tween:
		_tween.kill()
	_tween = create_tween().set_parallel(true)
	# everything that is not the new track fades out (one player may still be fading from before)
	for p: AudioStreamPlayer in [_music_a, _music_b]:
		if p.playing and (p != incoming or s == null):
			_tween.tween_property(p, "volume_db", -80.0, fade)
			_tween.tween_callback(func() -> void:
				if p != _cur:
					p.stop()).set_delay(fade)
	if s:
		incoming.stream = s
		incoming.volume_db = -40.0
		incoming.play()
		_tween.tween_property(incoming, "volume_db", MUSIC_DB, fade)
	_cur = incoming if s else null
	_t_acc = 0.0


func current_track() -> String:
	return _track


## Where the music is, in seconds of its own time: the mix head. A layer's volume change takes
## effect at the mix head, so output latency cancels out of the scheduling (the heard layer and
## the heard bar are late by the same amount). Stems report their position; the v1 boss intro
## cannot, so its time is counted by frames while it plays (frames stop with a hidden page).
func music_pos() -> float:
	if _cur == null or not _cur.playing:
		return 0.0
	if _cur.stream is AudioStreamInteractive:
		return _t_acc
	return _cur.get_playback_position() + AudioServer.get_time_since_last_mix()


## The bar clock of the current track: {pos, beat, bar, to_next_beat, to_next_bar} in seconds;
## {} with no track playing. Intros are whole bars, so the phase is position mod bar.
func bar_clock() -> Dictionary:
	if _cur == null or not TRACKS.has(_track):
		return {}
	var beat := 60.0 / track_bpm(_track)
	var bar := beat * float((TRACKS[_track] as Dictionary).get("beats_per_bar", 4))
	var pos := music_pos()
	return {"pos": pos, "beat": beat, "bar": bar, "to_next_beat": beat - fposmod(pos, beat), "to_next_bar": bar - fposmod(pos, bar)}


## Turns an optional layer of the playing track on or off (drums, lead, p2, p3). The switch
## lands on the music's next bar with a 60 ms fade (the drums leave over a whole bar). Returns
## how long it waits.
func layer(name: String, on: bool) -> float:
	if not _layers.has(name) or layer_on(name) == on:
		return 0.0
	_layer_on[name] = on
	var ref: Array = _layers[name]
	var sync: AudioStreamSynchronized = ref[0]
	var i: int = ref[1]
	if _layer_tw.has(name) and _layer_tw[name]:
		(_layer_tw[name] as Tween).kill()
	var to := 0.0 if on else LAYER_OFF_DB
	var clk := bar_clock()
	if not is_inside_tree() or clk.is_empty():
		sync.set_sync_stream_volume(i, to)
		return 0.0
	var wait := float(clk["to_next_bar"])
	var fade := float(LAYER_FADE.get("%s_%s" % [name, "on" if on else "off"], LAYER_FADE_DEFAULT))
	if fade < 0.0:
		fade = -fade * float(clk["bar"])
	_layer_at[name] = float(clk["pos"]) + wait
	var tw := create_tween()
	tw.tween_interval(wait)
	tw.tween_method(func(db: float) -> void: sync.set_sync_stream_volume(i, db),
		sync.get_sync_stream_volume(i), to, maxf(0.01, fade))
	_layer_tw[name] = tw
	return wait


func layer_on(name: String) -> bool:
	return bool(_layer_on.get(name, false))


## The music position a layer's last switch lands on (tests).
func layer_due(name: String) -> float:
	return float(_layer_at.get(name, -1.0))


## How hard the music plays (sound-v2 §5.2): 0 base, 1 + drums, 2 + lead. Up at once (on the
## next bar); down only after it has wanted to for INTENSITY_HOLD seconds, unless `now` (a
## room clear).
func intensity(level: int, now := false) -> void:
	_int_want = level
	if level > _int or (now and level < _int):
		_set_intensity(level)


func intensity_level() -> int:
	return _int


func _set_intensity(level: int) -> void:
	_int = level
	_int_low_t = 0.0
	layer("drums", level >= 1)
	layer("lead", level >= 2)


func _update_intensity(dt: float) -> void:
	if _int_want < _int:
		_int_low_t += dt
		if _int_low_t >= INTENSITY_HOLD:
			_set_intensity(_int_want)
	else:
		_int_low_t = 0.0


# ------------------------------------------------------------------ the frame

## Web: publishes the Music bus's peak (dB) to the page twice a second, so tools/webtest.sh can
## check the music really plays (window.wandcraftMusicPeak), not just that some sound does.
var _pub_t := 0.0


func _process(dt: float) -> void:
	if _cur and _cur.playing:
		_t_acc += dt
	_update_intensity(dt)
	_update_state(dt)
	_update_spots(dt)
	flush()
	if not OS.has_feature("web"):
		return
	_pub_t -= dt
	if _pub_t > 0.0:
		return
	_pub_t = 0.5
	var bus := AudioServer.get_bus_index("Music")
	var db := maxf(AudioServer.get_bus_peak_volume_left_db(bus, 0), -200.0)
	JavaScriptBridge.eval("window.wandcraftMusicPeak = %.1f; window.wandcraftMusicTrack = '%s';" % [db, _track], true)
