class_name CreditsScreen
extends Screen
## D8: the credits. Who made it, where the sound comes from, and the licences the game must
## carry. The audio credits are generated by tools/audio.sh from the CC-BY rows of
## assets_src/audio/LICENSES.csv into scripts/audio/credits_data.gd (none today: every
## sound is generated in code). The Godot Engine notice and its third-party licences come from the
## engine itself, so they are always the ones this build was made with. Scrolls by dragging.

var _lines: Array = []    # [text, color, size]
var _scroll := 0.0
var _drag_y := -1.0


func _opened() -> void:
	_lines = lines()


## Every line of the credits, top to bottom: [text, colour, size].
static func lines() -> Array:
	var out: Array = []
	out.append(["WANDCRAFT", GOLD, 16])
	out.append(["", TEXT, 8])
	out.append(["Design, code, art and sound: Bar Moshe", TEXT, 8])
	out.append(["All art is drawn in code. All music and sound are generated in code.", MUTED, 8])
	var cc := audio_credits()
	if not cc.is_empty():
		out.append(["", TEXT, 8])
		out.append(["AUDIO", GOLD, 8])
		for c in cc:
			out.append(["%s by %s (%s)" % [c["title"], c["author"], c["license"]], TEXT, 8])
	out.append(["", TEXT, 8])
	out.append(["MADE WITH GODOT ENGINE", GOLD, 8])
	for l in Engine.get_license_text().split("\n"):
		out.append([l, MUTED, 8])
	out.append(["", TEXT, 8])
	out.append(["THIRD-PARTY COMPONENTS IN GODOT ENGINE", GOLD, 8])
	for info in Engine.get_copyright_info():
		out.append([String(info["name"]), TEXT, 8])
		for p in info["parts"]:
			for c in p["copyright"]:
				out.append(["  (c) " + String(c), MUTED, 8])
			out.append(["  licence: " + String(p["license"]), MUTED, 8])
	return out


## The CC-BY rows the credits must name (generated by tools/audio.sh).
static func audio_credits() -> Array:
	return CreditsData.AUDIO


func _paint() -> void:
	dim(0.94)
	var v := view()
	var sr := safe()
	var y := sr.position.y + 16 - _scroll
	for l in _lines:
		if y > sr.position.y - 4 and y < sr.end.y - 30:
			text_center(v.x / 2.0, y, l[0], l[1], l[2], "body" if l[2] > 8 else "small")
		y += 18.0 if l[2] > 8 else 10.0
	_max_scroll = maxf(0.0, y + _scroll - (sr.end.y - 40))
	button(Rect2(v.x / 2.0 - 60, sr.end.y - 28, 120, 26), "close", "BACK", "primary")


var _max_scroll := 0.0


func _input(ev: InputEvent) -> void:
	# drag to scroll (the base class handles the BACK button)
	if ev is InputEventScreenDrag or (ev is InputEventMouseMotion and (ev as InputEventMouseMotion).button_mask & MOUSE_BUTTON_MASK_LEFT):
		var dy: float = ev.relative.y
		_scroll = clampf(_scroll - dy, 0.0, _max_scroll)
	elif ev is InputEventMouseButton and (ev as InputEventMouseButton).pressed:
		var mb := ev as InputEventMouseButton
		if mb.button_index == MOUSE_BUTTON_WHEEL_DOWN:
			_scroll = clampf(_scroll + 20.0, 0.0, _max_scroll)
		elif mb.button_index == MOUSE_BUTTON_WHEEL_UP:
			_scroll = clampf(_scroll - 20.0, 0.0, _max_scroll)
	super._input(ev)


func _on_button(id: String) -> void:
	if id == "close":
		finished.emit({})
