#!/usr/bin/env bash
# Regenerates every sound effect and music cue into game/assets/audio/ (gen_audio.gd for the
# effects, gen_music.gd for the music, about 3 minutes), re-imports them, and keeps the
# licence manifest (assets_src/audio/LICENSES.csv) in step. Deterministic: run it twice,
# same bytes.
#
# Import settings: music loops (except the boss intro, which hands over to the loop) and
# every file is QOA-compressed in the build. Godot's WAV writer does not store loop points,
# so they are set in the .import files here.
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
source "$HERE/lib/platform.sh"
GAME="$HERE/../game"
AUDIO="$GAME/assets/audio"
MANIFEST="$HERE/../assets_src/audio/LICENSES.csv"

"$HERE/godot.sh" --headless --path "$GAME" --import >/dev/null 2>&1 || true   # registers Loudness
"$HERE/godot.sh" --headless --path "$GAME" -s "$HERE/gen_audio.gd"
"$HERE/godot.sh" --headless --path "$GAME" -s "$HERE/gen_music.gd"
"$HERE/godot.sh" --headless --path "$GAME" --import >/dev/null 2>&1 || true

for f in "$AUDIO"/*.wav.import; do
  base="$(basename "$f" .wav.import)"
  loop=1   # disabled
  case "$base" in
    music_boss_intro) loop=1 ;;
    music_*) loop=2 ;;   # forward
  esac
  sed_inplace -e "s/^edit\/loop_mode=.*/edit\/loop_mode=$loop/" -e "s/^compress\/mode=.*/compress\/mode=2/" "$f"
done
"$HERE/godot.sh" --headless --path "$GAME" --import >/dev/null 2>&1 || true

# the manifest: one row per shipped audio file. Rows for generated files are rewritten;
# any other row (a CC0 or CC-BY file added by hand later) is kept as it is.
mkdir -p "$(dirname "$MANIFEST")"
HEADER="file,title,source,license,author,credit_required"
tmp="$(mktemp)"
echo "$HEADER" > "$tmp"
if [ -f "$MANIFEST" ]; then
  tail -n +2 "$MANIFEST" | grep -v ',tools/gen_' >> "$tmp" || true
fi
for w in "$AUDIO"/*.wav; do
  b="$(basename "$w")"
  grep -q "^$b," "$tmp" && continue
  gen="tools/gen_audio.gd"
  case "$b" in music_*|sting_*) gen="tools/gen_music.gd" ;; esac
  title="$(echo "${b%.wav}" | sed 's/_/ /g')"
  echo "$b,$title,$gen,original,Bar Moshe (generated in code),no" >> "$tmp"
done
{ head -1 "$tmp"; tail -n +2 "$tmp" | sort; } > "$MANIFEST"
rm -f "$tmp"

# the credits screen names every CC-BY file (CreditsData.AUDIO)
CREDITS="$GAME/scripts/audio/credits_data.gd"
{
  echo "class_name CreditsData"
  echo "extends RefCounted"
  echo "## Generated by tools/audio.sh from the CC-BY rows of assets_src/audio/LICENSES.csv."
  echo "## Do not edit: add the row to the manifest and run tools/audio.sh."
  echo ""
  echo "const AUDIO := ["
  tail -n +2 "$MANIFEST" | awk -F, 'toupper($4) ~ /^CC-BY/ { printf "\t{\"file\": \"%s\", \"title\": \"%s\", \"license\": \"%s\", \"author\": \"%s\"},\n", $1, $2, $4, $5 }'
  echo "]"
} > "$CREDITS"
ls "$AUDIO"/*.wav | wc -l | xargs echo "audio files:"
