#!/usr/bin/env bash
# Writes an audition page for every shipped sound (shots/audiosheet.html): one player per
# file, grouped as music, ambience, stingers and effects by family, with length and size.
# Open it straight from disk (file://); the players load game/assets/audio/ by relative path.
# Usage: tools/audiosheet.sh
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
source "$HERE/lib/platform.sh"
ROOT="$(cd "$HERE/.." && pwd)"
AUDIO="$ROOT/game/assets/audio"
OUT="$ROOT/shots"
PAGE="$OUT/audiosheet.html"
mkdir -p "$OUT"

# a little-endian unsigned integer of `n` bytes at `off` in a file
le() { od -An -t u"$3" -j "$2" -N "$3" "$1" | tr -d ' \n'; }

# family of a file, for grouping
family() {
  case "$1" in
    music_amb_*) echo "Ambience" ;;
    music_*) echo "Music" ;;
    sting_*) echo "Stingers" ;;
    sfx_cast_*|sfx_trigger*) echo "Casts" ;;
    sfx_hit*|sfx_crit*|sfx_armor_*|sfx_ward_*) echo "Hits and defences" ;;
    sfx_kill*|sfx_boom*|sfx_bigboom*) echo "Kills and explosions" ;;
    sfx_eshot*|sfx_tele*|sfx_slam*|sfx_fuse*|sfx_summon*|sfx_charge*|sfx_bonk*|sfx_phase*|sfx_spawn*|sfx_roar*|sfx_chomp*|sfx_copy_cast*|sfx_ctrl_z*|sfx_select_all*|sfx_derail*) echo "Enemies and bosses" ;;
    sfx_hurt*|sfx_dash*|sfx_mana*|sfx_low_hp*|sfx_heal*|sfx_step*) echo "The player" ;;
    sfx_ui*|sfx_swap*|sfx_deny*|sfx_buy*) echo "UI" ;;
    *) echo "World and rewards" ;;
  esac
}

SECTIONS=("Music" "Ambience" "Stingers" "Casts" "Hits and defences" "Kills and explosions" "Enemies and bosses" "The player" "World and rewards" "UI")
count=0
total=0
{
  cat <<'HTML'
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Wandcraft Audio Sheet</title>
<style>
:root{--bg:#15121c;--card:#211c2b;--ink:#ece6f5;--dim:#a79fb8;--gold:#d9b25f;--line:#342c42}
@media (prefers-color-scheme: light){:root:not([data-theme="dark"]){--bg:#f6f2ea;--card:#fffdf8;--ink:#231d2e;--dim:#6b6278;--gold:#9a6f16;--line:#e2dacb}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.45 system-ui,-apple-system,sans-serif;padding:24px 16px}
h1{margin:0 0 4px;font-size:22px}p.sub{margin:0 0 20px;color:var(--dim)}
h2{font-size:16px;color:var(--gold);margin:28px 0 10px;border-bottom:1px solid var(--line);padding-bottom:6px}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:10px}
.c{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:10px 12px}
.n{font-family:ui-monospace,Menlo,monospace;font-size:13px;display:flex;justify-content:space-between;gap:8px}
.n span{color:var(--dim)}audio{width:100%;height:32px;margin-top:6px}
</style></head><body>
<h1>Wandcraft audio sheet</h1>
HTML
  echo "<p class=\"sub\">Generated by tools/audiosheet.sh on $(date '+%Y-%m-%d %H:%M'). Every file in game/assets/audio.</p>"
  for g in "${SECTIONS[@]}"; do
    rows=""
    for w in "$AUDIO"/*.wav; do
      b="$(basename "$w")"
      [ "$(family "$b")" = "$g" ] || continue
      size="$(file_size "$w")"
      rate="$(le "$w" 24 4)"
      ch="$(le "$w" 22 2)"
      bits="$(le "$w" 34 2)"
      secs="$(awk -v s="$size" -v r="$rate" -v c="$ch" -v b="$bits" 'BEGIN{ if (r*c*b>0) printf "%.2f", (s-44)/(r*c*b/8); else print "?" }')"
      kb=$(( size / 1024 ))
      rows+="<div class=\"c\"><div class=\"n\">${b%.wav}<span>${secs} s · ${kb} KB · $((rate/1000)) kHz$([ "$ch" = 2 ] && echo ' stereo' || true)</span></div><audio controls preload=\"none\" src=\"../game/assets/audio/$b\"></audio></div>"
      count=$((count + 1))
      total=$((total + size))
    done
    if [ -n "$rows" ]; then echo "<h2>$g</h2><div class=\"grid\">$rows</div>"; fi
  done
  echo "</body></html>"
} > "$PAGE"
echo "audiosheet: $count files, $((total / 1048576)) MB -> $PAGE"
