class_name IconRelicsB
extends RefCounted
## Relic icons for the 0.21 round (Area, summons, Shock, Frost and the rule relics). Same
## format as IconRelics (see IconArt for the legend): {"ramp", "acc", "rows": 12 x 12}.
## Data only, on the Style ramps.

const ART := {
	# Crowd Blast / Load Spike: a blast swelling in a ring of enemies
	&"load_spike": {"ramp": "ember", "acc": "steel", "rows": [
		"c..........c",
		"......4.....",
		"...4.434.4..",
		"....43w34...",
		"..443www344.",
		"....43w34...",
		"...4.434.4..",
		"......4.....",
		"c..........c",
		"............",
		".c..c..c..c.",
		"............",
	]},
	# Blast Share / Side Effects: one blast, and its statuses dripping onto two more enemies
	&"side_effects": {"ramp": "rose", "acc": "frost", "rows": [
		"............",
		"....333.....",
		"...34w43....",
		"...344443...",
		"....3332....",
		"..b..2..c...",
		".bab.2.cbc..",
		"..b..2..c...",
		"...222222...",
		"..33....33..",
		".34w3..34w3.",
		"..33....33..",
	]},
	# Scorch Zone / Burn-In: flames on a patch of scorched ground
	&"burn_in": {"ramp": "ember", "acc": "stone", "rows": [
		"............",
		"....4.......",
		"...4w4..4...",
		"...434.4w4..",
		"..43334434..",
		"..33223333..",
		"...2112322..",
		".aaaaaaaaaa.",
		"abbbbbbbbbba",
		"acbcbcbcbcba",
		".aaaaaaaaaa.",
		"............",
	]},
	# Aftershock / Chain Reaction: a blast and the smaller one it sets off
	&"chain_reaction": {"ramp": "gold", "acc": "ember", "rows": [
		"......4.....",
		"...4.434.4..",
		"....43w34...",
		"..443www344.",
		"....43w34...",
		"...4.434.4..",
		"......4.....",
		"........c...",
		"......c.bc.c",
		".......bab..",
		"........c...",
		"............",
	]},
	# Shared Boosts / Inheritance: a boost arrow over a summoned sprite
	&"inheritance": {"ramp": "violet", "acc": "gold", "rows": [
		"....cc......",
		"...cbbc.....",
		"..c.bb.c....",
		"....bb......",
		"....bb......",
		".....4444...",
		"....4w4444..",
		"....44oo44..",
		"....444444..",
		".....4444...",
		"....4.44.4..",
		"............",
	]},
	# Summon Refund / Graceful Exit: a summon fading out, its mana dropping back
	&"graceful_exit": {"ramp": "leaf", "acc": "violet", "rows": [
		"............",
		"..a.a.......",
		".abbba......",
		".bcoba......",
		".abbba..4...",
		"..a.a..4w4..",
		".......444..",
		"..2...44w44.",
		".22222444443",
		"..2...34443.",
		".......333..",
		"............",
	]},
	# Summon Volley / Hive Mind: three summons firing together
	&"hive_mind": {"ramp": "amber", "acc": "cyan", "rows": [
		"............",
		".33.........",
		"3w43.cc.cc..",
		".33.........",
		"............",
		".33.........",
		"3w43.cc.cc..",
		".33.........",
		"............",
		".33.........",
		"3w43.cc.cc..",
		".33.........",
	]},
	# Shock Charge / Live Wire: a bolt that leaves its target charged
	&"live_wire": {"ramp": "cyan", "acc": "gold", "rows": [
		"......cc....",
		".....cc.....",
		"....cc......",
		"...cccccc...",
		"......cc....",
		".....cc.....",
		"....c.......",
		"..444444....",
		".4w.....4...",
		".4.oooo.4...",
		".4......4...",
		"..333333....",
	]},
	# Charged Strike / Overvoltage: a charged orb cracking under a hit
	&"overvoltage": {"ramp": "gold", "acc": "blood", "rows": [
		"...........c",
		"..........c.",
		"....4444.c..",
		"...4w444cc..",
		"..4w444c44..",
		"..444c4444..",
		"..44c44443..",
		"..4c444443..",
		"...44443c...",
		"....333.....",
		"...c........",
		"............",
	]},
	# Frost Spread / Cold Spill: a snowflake over the chill it spills
	&"cold_spill": {"ramp": "frost", "acc": "steel", "rows": [
		"............",
		".....4......",
		"...4.4.4....",
		"....444.....",
		"..4444w44...",
		"....444.....",
		"...4.4.4....",
		".....4......",
		".3.......3..",
		"323.....323.",
		".3...3...3..",
		".....3......",
	]},
	# Quick Freeze / Flash Freeze: an ice block with a quick spark
	&"flash_freeze": {"ramp": "frost", "acc": "gold", "rows": [
		"..........c.",
		"...4444444c.",
		"..4w444443..",
		".4w444443.3.",
		".44444443.3.",
		".43333333.3.",
		".43333332.2.",
		".43333332.2.",
		".43333332.2.",
		".4333333322.",
		".22222222...",
		"............",
	]},
	# Clean Streak / Clean Build: a check mark over a streak of bars
	&"clean_build": {"ramp": "leaf", "acc": "gold", "rows": [
		"............",
		"..........4.",
		".........4w.",
		"........44..",
		".4.....44...",
		".44...44....",
		"..44.44.....",
		"...444......",
		"....4.......",
		"............",
		".c.cc.ccc...",
		".c.cc.ccc...",
	]},
	# Risky Code / Hotfix: a patch slapped over a crack, still sparking
	&"risky_code": {"ramp": "glitch", "acc": "ember", "rows": [
		"............",
		".......444..",
		"......4w443.",
		".....4w4443.",
		"....4ww4o3..",
		"...4w4o432..",
		"..4w44432...",
		".44o4432....",
		".4444432.c..",
		"..33332..cb.",
		"........c...",
		"............",
	]},
	# Relic Copy / git clone: a relic and the copy it becomes
	&"git_clone": {"ramp": "steel", "acc": "arcane", "rows": [
		"............",
		".444444.....",
		".4w4444.....",
		".44bbbbbb...",
		".44bcccccb..",
		".44bcwcccb..",
		".333bccccb..",
		"....bccccb..",
		"....bccccb..",
		"....abbbba..",
		"............",
		"............",
	]},
	# Fixed Vitals / Version Pin: a heart pinned in place
	&"version_pin": {"ramp": "blood", "acc": "steel", "rows": [
		"...........c",
		"..33..33..c.",
		".3w433443c..",
		".3444444c3..",
		".344444c43..",
		"..3444c443..",
		"...34c443...",
		"....c443....",
		"...c.33.....",
		"..c...3.....",
		".a..........",
		"............",
	]},
	# Wand Variety / Code Coverage: three wands, each worn a little differently
	&"code_coverage": {"ramp": "arcane", "acc": "gold", "rows": [
		"............",
		"..c...c...c.",
		".cwc.cwc.cwc",
		"..c...c...c.",
		"..4...4...4.",
		"..4...4...4.",
		"..4...4...3.",
		"..4...3...3.",
		"..3...3...2.",
		"..3...2.....",
		"..2.........",
		"............",
	]},
}
