class_name IconSpellsE
extends RefCounted
## Icon illustrations for the 0.20 arsenal (research/arsenal-0.20: 6-spells-wands.md for the
## spells, 7-relics.md for the relics). Same format as IconSpells and IconRelics (see IconArt
## for the legend): ART holds the spells, RELICS the relics. Data only.

const ART := {
	# a slow grinding bit: spiral flutes on a cone, the gold chuck behind it
	&"drill_bit": {"ramp": "steel", "acc": "gold", "kind": "proj", "rows": [
		"............",
		"............",
		"...44w3.....",
		".cb4w324....",
		"bcb3244w3...",
		"cbb2w4324w3.",
		"bba24w3224w4",
		".aa3244w32..",
		"...2324w..c.",
		".........c.c",
		"..........c.",
		"............",
	]},
	# a tiny bomb zipped shut: a zipper down its middle, the pull tab up top, a fuse spark
	&"zip_bomb": {"ramp": "violet", "acc": "gold", "kind": "proj", "rows": [
		".........w..",
		"........wcw.",
		".......b.w..",
		"....33b.....",
		"...34cc43...",
		"..34wcw443..",
		"..344bc4432.",
		"..344cb4432.",
		"..333bc3322.",
		"...23cb322..",
		"....2222....",
		"............",
	]},
	# a blue screen field with a frown and a line of crash text
	&"blue_screen": {"ramp": "arcane", "acc": "gold", "kind": "proj", "rows": [
		"...c........",
		".4444444443.",
		".4333333332.",
		".43w33w3332.",
		".43w33w3332.",
		".4333333332.",
		".4333ww3332.",
		".433w33w332.",
		".4333333332.",
		".4w4w4ww432.",
		".2222222221.",
		"........c...",
	]},
	# a sticky tar ball holding two sparks, one drip hanging below
	&"tarball": {"ramp": "stone", "acc": "gold", "kind": "proj", "rows": [
		"............",
		"....3333....",
		"..334w4322..",
		".34w322c222.",
		".3432.cwc21.",
		".332222c221.",
		".32b2222221.",
		".2bwb222c21.",
		".22b222cwc1.",
		"..22222.c1..",
		"....21.11...",
		".....1......",
	]},
	# wait for the hit: an hourglass, then an arrow flies to the struck star
	&"await_hit": {"ramp": "cyan", "acc": "gold", "kind": "trig", "rows": [
		"............",
		"bbbbb.......",
		".cwc........",
		"..c.........",
		".c.b........",
		"bbbbb..3.4.3",
		"....4....w..",
		"123344.4www4",
		"....4....w..",
		".......3.4.3",
		"............",
		"............",
	]},
	# a loading spinner: eight dots, the head bright, the tail fading
	&"buffering": {"ramp": "cyan", "kind": "boost", "rows": [
		"............",
		".....44.ww..",
		"..44.44.ww..",
		"..44......4.",
		"..........44",
		".33.......44",
		".33.........",
		".........22.",
		"..33.....22.",
		"..33.22.....",
		".....22.....",
		"............",
	]},
	# a circular retry arrow around the spell it gives a second try
	&"retry": {"ramp": "leaf", "kind": "boost", "rows": [
		"............",
		"....4444....",
		"...4.....w..",
		"..4.....444.",
		"..4....44444",
		"..4..ww..3..",
		"..4..ww..3..",
		"..3......3..",
		"...3....3...",
		"....3333....",
		"............",
		"............",
	]},
	# just in time: a clock face with a lightning bolt struck across it
	&"jit": {"ramp": "toxic", "acc": "gold", "kind": "boost", "rows": [
		"............",
		"....3333.cc.",
		"...3....cc..",
		"..3..4.cc...",
		"..3..4cccc..",
		"..3..444cc..",
		"..3.....c...",
		"...3...c3...",
		"....333c....",
		".......c....",
		"............",
		"............",
	]},
	# a closing curly brace: the boosts on its left stop here
	&"end_scope": {"ramp": "violet", "kind": "boost", "rows": [
		"............",
		"....w443....",
		"......44....",
		"......44....",
		"......44....",
		".......4w4..",
		".2.2.3.332..",
		"......33....",
		"......33....",
		"......33....",
		"....3332....",
		"............",
	]},
	# Alt+Tab: two stacked windows and the arrow that swaps them
	&"alt_tab": {"ramp": "arcane", "acc": "gold", "kind": "rune", "rows": [
		"............",
		".2222222....",
		".2111112....",
		".21..12.....",
		".21.44444444",
		".21.4wwwwww4",
		".22243333333",
		"....43333332",
		"..c.43333332",
		".ccc43333332",
		"..c.22222222",
		"..cccc......",
	]},
	# a text cursor with its ghost suggestion trailing to the right
	&"autocomplete": {"ramp": "cyan", "kind": "rune", "rows": [
		"............",
		"............",
		"......w.....",
		"44.43.w.222.",
		"4w.4w.w.2.2.",
		"43.43.w.2.2.",
		"33.33.w.222.",
		"......w.....",
		"......w.....",
		"............",
		"............",
		"............",
	]},
	# three key caps, the last one Delete
	&"ctrl_alt_del": {"ramp": "bone", "acc": "blood", "kind": "rune", "rows": [
		"............",
		"............",
		"............",
		"444.444.ccc.",
		"4w3.4w3.cwb.",
		"433.433.cbb.",
		"222.222.aaa.",
		"111.111.aaa.",
		"............",
		"............",
		"............",
		"............",
	]},
	# a memory stick with a dotted extension past its end
	&"virtual_memory": {"ramp": "leaf", "acc": "gold", "kind": "passive", "rows": [
		"............",
		"............",
		"............",
		"44444443.2.2",
		"4o1o1o13....",
		"4o1o1o13...2",
		"44444443....",
		"3333333.2.2.",
		"c.c.c.c.....",
		"b.b.b.b.2.2.",
		"............",
		"............",
	]},
	# a target struck by a lightning check mark
	&"cache_hit": {"ramp": "rose", "acc": "gold", "kind": "passive", "rows": [
		"..333.......",
		".3...3......",
		"3..4..3....c",
		"3.4w4.3...cb",
		"3..4..3..cb.",
		".3...3..cb..",
		"..333..cb...",
		".c.....cb...",
		".cc..ccb....",
		"..cc.cb.....",
		"...ccb......",
		"....b.......",
	]},
}

const RELICS := {
	# Locked Fury: a padlock holding a slot shut, fury rising beside it
	&"graceful_degrade": {"ramp": "glitch", "acc": "gold", "rows": [
		"........c...",
		"..333..ccc..",
		".3...3cccc..",
		".3...3..c...",
		"4444442.c...",
		"4w44442.c...",
		"444oo42.c...",
		"444oo42.....",
		"4444o42.....",
		"3333332.....",
		"............",
		"............",
	]},
	# Puddle Skater: a mana drop skating over a leak puddle, speed lines behind
	&"swap_space": {"ramp": "cyan", "acc": "gold", "rows": [
		"............",
		".......4....",
		"......4w4...",
		"b.b..4ww44..",
		".....44443..",
		"b.b..44443..",
		"......333...",
		"............",
		"..33333333..",
		".3444444442.",
		"..22222222..",
		"............",
	]},
	# Finisher / join(): two threads meet in one point that finishes the target
	&"thread_join": {"ramp": "violet", "acc": "gold", "rows": [
		"4..........c",
		".4........c.",
		"..4......c..",
		"...4....c...",
		"....4..c....",
		".....ww.....",
		".....ww.....",
		".....43.....",
		"...b.43.b...",
		"....b33b....",
		"..bb.22.bb..",
		"....b..b....",
	]},
	# Take-Back / Undo Stack: an undo arrow curling back over a stack of layers
	&"undo_stack": {"ramp": "leaf", "acc": "steel", "rows": [
		"...4........",
		"..44444.....",
		".4w44444....",
		"..44...44...",
		"...4....4...",
		"........4...",
		"..cccccc....",
		".cbbbbbba...",
		"..cccccc....",
		".cbbbbbba...",
		"..cccccc....",
		".abbbbbba...",
	]},
	# Warm-Up / Cache Warmup: a memory chip with a flame warming it
	&"warm_cache": {"ramp": "ember", "acc": "steel", "rows": [
		".....3......",
		"....343.....",
		"...3443..3..",
		"...34w43.3..",
		"..34ww443...",
		"..34ww443...",
		".b.b.b.b.b..",
		"cccccccccb..",
		"cb.a.a.a.a..",
		"cb.a.a.a.a..",
		"bbbbbbbbba..",
		".a.a.a.a.a..",
	]},
	# Tail Boost / Hoisting: a crane hook lifting a boost gem
	&"hoisting": {"ramp": "steel", "acc": "cyan", "rows": [
		"44444444444.",
		".....4......",
		".....4......",
		".....4......",
		"....343.....",
		"....3.3.....",
		"......3.....",
		".....cb.....",
		"....cwcb....",
		"...cwcccb...",
		"....cccb....",
		".....cb.....",
	]},
	# Mixed Program / Polyglot: one of each spell plate, round, diamond, square, hexagon
	&"polyglot": {"ramp": "cyan", "acc": "gold", "rows": [
		"............",
		".333....c...",
		"34w43..cwc..",
		"34443.ccccc.",
		".333...ccc..",
		"........c...",
		"............",
		".bbbbb..444.",
		".bwccb.4ww43",
		".bcccb.44443",
		".bbbba..333.",
		"............",
	]},
	# Short Wand / Short-Circuit: three slots and a bolt jumping over them
	&"short_circuit": {"ramp": "gold", "acc": "steel", "rows": [
		".......44...",
		"......44....",
		".....44.....",
		"....4444w...",
		".......44...",
		"......44....",
		".....4......",
		"............",
		"cccc.cccc.cc",
		"c4wb.cb.b.cb",
		"c44b.cb.b.cb",
		"bbba.bbba.ba",
	]},
	# Buyback / End of Life: a tombstone, a gold coin paid out in front
	&"end_of_life": {"ramp": "stone", "acc": "gold", "rows": [
		"...4444.....",
		"..444443....",
		".44w44443...",
		".4444w443...",
		".44w4w443...",
		".44w44443...",
		".4444443....",
		".4443.ccc...",
		".4443cwcbb..",
		".4443ccbba..",
		"33333cbbba..",
		"......aaa...",
	]},
	# Technical Debt: a ball and chain, the shackle cracked with corruption
	&"technical_debt": {"ramp": "steel", "acc": "glitch", "rows": [
		".444........",
		"4w..4.......",
		"4...4.......",
		".3333.......",
		"....3.3.....",
		"......3.33..",
		".......3w443",
		"......34ww43",
		"......344c43",
		"..c...34c432",
		".c.c..233322",
		"..c....2222.",
	]},
	# Refund Misses / Lazy Evaluation: a mana drop with the arrow that returns it
	&"lazy_eval": {"ramp": "arcane", "acc": "gold", "rows": [
		"............",
		"...4........",
		"..4w4.......",
		".4w443c.c.c.",
		".444433....c",
		".344432....b",
		"..3332.....c",
		"...........b",
		"...c.......c",
		"..ccc......b",
		"...cbcbcbcba",
		"............",
	]},
	# Swap Dodge / Context Switch: two wands and the arrows that swap them
	&"context_switch": {"ramp": "violet", "acc": "gold", "rows": [
		"cw........4w",
		"bc........34",
		"..b......3..",
		"...b....3...",
		"....b..3....",
		".....b3.....",
		".....3b.....",
		"....3..b....",
		"..4.........",
		".4444444..c.",
		"..4.cccccccc",
		"..........c.",
	]},
	# Bit Savings / Cold Storage: a frosted vault with a dial, a bit coin on the side
	&"cold_storage": {"ramp": "frost", "acc": "gold", "rows": [
		".ww.ww.ww...",
		"wwwwwwwww...",
		"4444444443..",
		"4......23..c",
		"4..444.23.cw",
		"4..4w4.23.cb",
		"4..444.23..a",
		"4......23...",
		"4.....423...",
		"4333333332..",
		".2.....2....",
		"............",
	]},
	# Contagion / Shared Memory: two cells overlapping, the shared part bright
	&"shared_memory": {"ramp": "toxic", "acc": "violet", "rows": [
		"............",
		"..333..bbb..",
		".3...3b...b.",
		"3..4.www.c.b",
		"3.4..www...b",
		"3....www...b",
		"3....www...b",
		".3...3a...a.",
		"..333..aaa..",
		"............",
		"............",
		"............",
	]},
	# Double Tick / Cron Job: a clock face and two ticks under it
	&"cron_job": {"ramp": "violet", "acc": "leaf", "rows": [
		"...3333.....",
		"..3.4..3....",
		".3..4...3...",
		".3..444.3...",
		".3......3...",
		"..3....3....",
		"...3333.....",
		"...........c",
		"..c...c...cc",
		"...c.cc..cc.",
		"....ccc.cc..",
		".....c...c..",
	]},
	# Cold Current / Superconductor: an ice bolt that forks to one more target
	&"superconductor": {"ramp": "frost", "acc": "cyan", "rows": [
		"c.c.c....44.",
		".ccc....44..",
		"ccwcc..44...",
		".ccc..4www4.",
		"c.c.c...44..",
		".......44...",
		"......4w....",
		".....4..4...",
		"....4....4..",
		"...w......w.",
		"............",
		"............",
	]},
}
