class_name PixelArt
extends RefCounted
## Procedural pixel-art toolkit: ASCII sprites with palettes, top-left shading, 1px outlines,
## glow sprites and cached ImageTextures. Everything is deterministic, so art can be
## regenerated by tools/ or swapped for hand-made PNGs later.

const OUTLINE := Color("#0a0714")

static var _tex_cache: Dictionary = {}


## Builds an image from ASCII rows. `pal` maps single characters to "#rrggbb" strings.
static func from_rows(rows: PackedStringArray, pal: Dictionary, outline := true, shade := true) -> Image:
	var h := rows.size()
	var w := rows[0].length()
	var img := Image.create_empty(w, h, false, Image.FORMAT_RGBA8)
	for j in h:
		var row: String = rows[j]
		for i in mini(w, row.length()):
			var ch := row[i]
			if pal.has(ch):
				img.set_pixel(i, j, Color(pal[ch]))
	if shade:
		shade_image(img)
	if outline:
		img = outlined(img)
	return img


## Rim light from the top-left, shade toward the bottom-right and the lower half.
static func shade_image(img: Image, k := 1.0) -> void:
	var w := img.get_width()
	var h := img.get_height()
	var src := img.duplicate() as Image
	for j in h:
		for i in w:
			var c := src.get_pixel(i, j)
			if c.a == 0.0:
				continue
			var m := 0.0
			if j == 0 or src.get_pixel(i, j - 1).a == 0.0: m += 0.28
			if i == 0 or src.get_pixel(i - 1, j).a == 0.0: m += 0.12
			if j == h - 1 or src.get_pixel(i, j + 1).a == 0.0: m -= 0.30
			if i == w - 1 or src.get_pixel(i + 1, j).a == 0.0: m -= 0.16
			m -= (float(j) / h - 0.45) * 0.22
			m *= k
			img.set_pixel(i, j, c.lerp(Color.WHITE, m) if m > 0.0 else c.darkened(-m))


## Adds a 1px dark outline around every opaque pixel.
static func outlined(src: Image) -> Image:
	var w := src.get_width() + 2
	var h := src.get_height() + 2
	var out := Image.create_empty(w, h, false, Image.FORMAT_RGBA8)
	for j in src.get_height():
		for i in src.get_width():
			if src.get_pixel(i, j).a > 0.0:
				for dj in 3:
					for di in 3:
						out.set_pixel(i + di, j + dj, OUTLINE)
	out.blend_rect(src, Rect2i(0, 0, src.get_width(), src.get_height()), Vector2i(1, 1))
	return out


static func flipped(img: Image) -> Image:
	var c := img.duplicate() as Image
	c.flip_x()
	return c


static func tinted(img: Image, color: Color) -> Image:
	var c := img.duplicate() as Image
	for j in c.get_height():
		for i in c.get_width():
			var p := c.get_pixel(i, j)
			if p.a > 0.0:
				c.set_pixel(i, j, Color(color.r, color.g, color.b, p.a))
	return c


static func tex(img: Image) -> ImageTexture:
	return ImageTexture.create_from_image(img)


## Cached texture by key; `make` builds the Image on first use.
static func cached(key: String, make: Callable) -> Texture2D:
	if not _tex_cache.has(key):
		_tex_cache[key] = tex(make.call())
	return _tex_cache[key]


## Soft radial glow (white, alpha falloff) for additive sprites and bullets.
static func glow_texture(size := 32) -> Texture2D:
	return cached("glow%d" % size, func() -> Image:
		var img := Image.create_empty(size, size, false, Image.FORMAT_RGBA8)
		var r := size / 2.0
		for j in size:
			for i in size:
				var d := Vector2(i + 0.5 - r, j + 0.5 - r).length() / r
				if d < 1.0:
					var a := pow(1.0 - d, 2.2)
					img.set_pixel(i, j, Color(1, 1, 1, a))
		return img)


## Hard-edged round bullet core (3 tones) of a given radius.
static func bullet_texture() -> Texture2D:
	return cached("bullet", func() -> Image:
		var img := Image.create_empty(8, 8, false, Image.FORMAT_RGBA8)
		for j in 8:
			for i in 8:
				var d := Vector2(i + 0.5 - 4.0, j + 0.5 - 4.0).length()
				if d < 2.2:
					img.set_pixel(i, j, Color.WHITE)
				elif d < 3.6:
					img.set_pixel(i, j, Color(1, 1, 1, 0.75))
		return img)
